# Loading libraries

In [1]:
# Import the relevant libraries

import pandas as pd
import re
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

# Create DataFrames from excel sheets containing data

In [2]:
# Create data frames out of cohort 1 data excel sheets

c1_baseline = pd.read_excel('cohort 1.xlsx', sheet_name='cohort 1-baseline')
c1_acute = pd.read_excel('cohort 1.xlsx', sheet_name='cohort1-Acute')
c1_post = pd.read_excel('cohort 1.xlsx', sheet_name='Cohort1-4 week')

# Create dataframes out of cohort 2 data excel sheets

c2_baseline = pd.read_excel('cohort 2.xlsx', sheet_name='cohort 2-baseline')
c2_acute = pd.read_excel('cohort 2.xlsx', sheet_name='cohort 2-acute')
c2_post = pd.read_excel('cohort 2.xlsx', sheet_name='Cohort 2-4 weeks')

# Create dataframes out of ceremony data excel sheets

ceremony_baseline = pd.read_excel('ceremony.xlsx', sheet_name='Baseline')
ceremony_acute_1 = pd.read_excel('ceremony.xlsx', sheet_name='Acute-1')
ceremony_acute_2 = pd.read_excel('ceremony.xlsx', sheet_name='Acute-2')
ceremony_acute_3 = pd.read_excel('ceremony.xlsx', sheet_name='Acute-3')
ceremony_acute_4 = pd.read_excel('ceremony.xlsx', sheet_name='Acute-4')
ceremony_acute_5 = pd.read_excel('ceremony.xlsx', sheet_name='Acute-5')
ceremony_post = pd.read_excel('ceremony.xlsx', sheet_name='4 weeks')

# This will remove rows where NaNs are in 'URL Variable: sguid' column

c1_baseline = c1_baseline.dropna(subset=['URL Variable: sguid'])
c1_acute = c1_acute.dropna(subset=['URL Variable: sguid'])
c1_post = c1_post.dropna(subset=['URL Variable: sguid'])

c2_baseline = c2_baseline.dropna(subset=['URL Variable: sguid'])
c2_acute = c2_acute.dropna(subset=['URL Variable: sguid'])
c2_post = c2_post.dropna(subset=['URL Variable: sguid'])

ceremony_baseline = ceremony_baseline.dropna(subset=['URL Variable: sguid'])
ceremony_acute_1 = ceremony_acute_1.dropna(subset=['URL Variable: sguid'])
ceremony_acute_2 = ceremony_acute_2.dropna(subset=['URL Variable: sguid'])
ceremony_acute_3 = ceremony_acute_3.dropna(subset=['URL Variable: sguid'])
ceremony_acute_4 = ceremony_acute_4.dropna(subset=['URL Variable: sguid'])
ceremony_acute_5 = ceremony_acute_5.dropna(subset=['URL Variable: sguid'])
ceremony_post = ceremony_post.dropna(subset=['URL Variable: sguid'])

# Merging datasets together

In [3]:
# This will set the 'URL Variable: sguid' as index (i.e, column 0).

# Each survey participant has a unique 'URL Variable: sguid' and this is what
# should be used to track their responses through time.

# This operation is necessary to later merge the different timepoints
# and match them by participants.

# The following rows will set URL Variable: sguid as index for cohort 1

c1_baseline.set_index('URL Variable: sguid', inplace=True, drop=True)
c1_acute.set_index('URL Variable: sguid', inplace=True, drop=True)
c1_post.set_index('URL Variable: sguid', inplace=True, drop=True)

# Please note that due to overlapping numbering of rows in both cohorts,
# before setting 'URL Variable: sguid' as an index for Cohort 2,
# we will add number '2000' to the Response ID for cohort 2 subjects.
# This will allow us to distinguish between the cohorts.

# This means data for every Subject ID > 2000 is from cohort 2

# 2000 is a random number chosen just to make it easy, 
# there is no other logic behind that choice. 

c2_baseline[["Response ID"]] = c2_baseline[["Response ID"]] + 2000
c2_acute[["Response ID"]] = c2_acute[["Response ID"]] + 2000
c2_post[["Response ID"]] = c2_post[["Response ID"]] + 2000

# The following rows will set URL Variable: squid as index for cohort 2

c2_baseline.set_index('URL Variable: sguid', inplace=True, drop=True)
c2_acute.set_index('URL Variable: sguid', inplace=True, drop=True)
c2_post.set_index('URL Variable: sguid', inplace=True, drop=True)

# The following rows will set URL Variable: squid as index for ceremony data

ceremony_baseline.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_acute_1.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_acute_2.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_acute_3.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_acute_4.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_acute_5.set_index('URL Variable: sguid', inplace=True, drop=True)
ceremony_post.set_index('URL Variable: sguid', inplace=True, drop=True)

# Renaming columns

### Cohort 1

#### Baseline

In [4]:
# Renaming columns names for cohort 1 baseline

c1_baseline = (c1_baseline.rename(columns={'URL Variable: sguid': 'URL',
            "Response ID": 'ID_baseline',
            "Country": 'Country_baseline',
            'City':'City_baseline',                               
            "Your age:": 'age',
            "Your gender:": 'gender',
            "Nationality (e.g. GB = British; US = USA):": 'nationality',
            "Highest educational level attained:": 'education',
            "Employment:": 'Employment',
            "LSD:Please indicate what psychedelics you have used in the past. ¬†": 'LSD use',
            "DMT:Please indicate what psychedelics you have used in the past. ¬†": 'DMT use',
            "Ayahuasca:Please indicate what psychedelics you have used in the past. ¬†": 'Ayahuasca use',
            "Psilocybin / magic mushrooms / truffles:Please indicate what psychedelics you have used in the past. ¬†": 'psychedelics use',
            "Mescaline (Peyote, San Pedro):Please indicate what psychedelics you have used in the past. ¬†": 'Mescaline use',
            "Salvia Divinorum:Please indicate what psychedelics you have used in the past. ¬†": 'Salvia Divinorum use',
            "Iboga / Ibogaine:Please indicate what psychedelics you have used in the past. ¬†": 'Iboga use',
            "Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, 2C-B, 4-ACO-DMT, 1P-LSD):Please indicate what psychedelics you have used in the past. ¬†": 'Hallucinogen use',
            "Other - Write In:Please indicate what psychedelics you have used in the past. ¬†": 'Other use',
            "None of the above:Please indicate what psychedelics you have used in the past. ¬†": 'None psychedelics use',
            "Other - Write In:Please indicate what psychedelics you have used in the past. ¬†.1": 'other1 use',
            "Please indicate the number of times you have taken classic psychedelic substances (LSD, psilocybin, DMT, ayahuasca, mescaline).": 'number of times you have taken psychedelic',
            "Amphetamines:Please indicate what other drugs you have used at least once.": 'Amphetamines use',
            "MDMA/Ecstasy:Please indicate what other drugs you have used at least once.": 'MDMA/Ecstasy use',
            "Cocaine:Please indicate what other drugs you have used at least once.": 'Cocaine use',
            "Opiates:Please indicate what other drugs you have used at least once.": 'Opiates use',
            "Benzodiazepines:Please indicate what other drugs you have used at least once.": 'Benzodiazepines use',
            "Ketamine:Please indicate what other drugs you have used at least once.": 'Ketamine use',
            "None of the above:Please indicate what other drugs you have used at least once.": 'None drugs use',
            
            "Major depressive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Major depressive disorder',
            "Bipolar disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Bipolar disorder',
            "Schizophrenia:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Schizophrenia',
            "Anxiety disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Anxiety disorder',
            "Substance abuse disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Substance abuse disorder',
            "Alcohol dependence:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Alcohol dependence',
            "Hallucinogen persisting perception disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Hallucinogen persisting perception disorder',
            "Psychotic disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Psychotic disorder',
            "Personality disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Personality disorder',
            "ADHD:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'ADHD',
            "Obsessive compulsive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Obsessive compulsive disorder',
            "Eating disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Eating disorder',
            "None of the above:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'No disorder',
           
            "Have you ever been treated with medication(s) for the illness(es) stated above?": 'treated with medications',
            "Are you currently using this/these medication(s)?": 'Current use',
            "Anti-depressants:What is your current prescribed medication?": 'Anti-depressants',
            "Mood stabilisers:What is your current prescribed medication?": 'Mood stabilisers',
            "Anti-psychotics:What is your current prescribed medication?": 'Anti-psychotics',
            "ADHD medication:What is your current prescribed medication?": 'ADHD medication',
            "Medication for substance abuse disorder:What is your current prescribed medication?": 'substance abuse disorder meds',
            "Medication for alcohol dependence:What is your current prescribed medication?": 'alcohol dependence meds',
            "None of the above:What is your current prescribed medication?": 'No current meds',    
    
            "What type of compound do you anticipate to take in your upcoming experience?": 'compound to take',
            "Other - Write In:What type of compound do you anticipate to take in your upcoming experience?": 'other compound',
            "Fun / recreational / party:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Fun / recreational / party',
            "Therapeutic / personal growth:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Therapeutic / personal growth',
            "Medicinal:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Medicinal',
            "Spiritual experience:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Spiritual experience',
            "Religious practice:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Religious practice',
            "Curiosity:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Curiosity',
            "Social:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Social',
            "Connection with nature:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'Connection with nature',
            "To escape from difficult emotions:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'escape from difficult emotions',
            "To confront difficult emotions:Can you indicate what your motives are to undergo a psychedelic session/ceremony/experience?": 'confront difficult emotions',
                
            #Baseline Well-being
            "I've been feeling optimistic about the future.": 'WEMWBS1_baseline',
            "I've been feeling useful.": 'WEMWBS2_baseline',
            "I've been feeling relaxed.": 'WEMWBS3_baseline',
            "I've been feeling interested in other people.¬†": 'WEMWBS4_baseline',
            "I've had energy to spare.": 'WEMWBS5_baseline',
            "I've been dealing with problems well.¬†": 'WEMWBS6_baseline',
            "I've been thinking clearly.": 'WEMWBS7_baseline',
            "I've been feeling good about myself.¬†": 'WEMWBS8_baseline',
            "I've been feeling close to other people.¬†": 'WEMWBS9_baseline',
            "I've been feeling confident.": 'WEMWBS10_baseline',
            "I've been able to make up my own mind about things.¬†": 'WEMWBS11_baseline',
            "I've been feeling loved.¬†": 'WEMWBS12_baseline',
            "I am interested in new things.¬†": 'WEMWBS13_baseline',
            "I've been feeling cheerful.¬†": 'WEMWBS14_baseline'}))

#### Acute

In [5]:
# Renaming columns names for cohort 1 acute

c1_acute = (c1_acute.rename(columns={"URL Variable: sguid": 'URL',
            "Country": 'Country_acute',                        
            "Response ID": 'ID_acute',
            "Which substance did you use in the psychedelic session/ceremony/experience?": 'used substance',
            "Other - Write In:Which substance did you use in the psychedelic session/ceremony/experience?": 'other substance',
            "How did you administer the drug/medicine?": 'rote of administration',
            "Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD. For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. ¬†": 'total dose',
            "If you know the exact dose you may write it here: (please also remind us what drug you are referring to) ¬†": 'exact dose',
            "Cannabis:Can you indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Cannabis',
            "Alcohol:Can you indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Alcohol',
            "Stimulants (e.g. amphetamines, cocaine):Can you indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Stimulants',
            "Tobacco:Can you indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Tobacco',
            "MDMA/ecstasy:Can you indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'MDMA/ecstasy',
            
            #Acute Questionnaires
            #ASC for cohort 1 
            "I felt like a doll on a string or a marionette.": 'ASC1_Average',
            "I felt connected to a higher power.": 'ASC2_Average',
            "I experienced boundless joy.": 'ASC3_Average',
            "I saw regular patterns in complete darkness or with closed eyes.": 'ASC4_Average',
            "All things seemed to unify as a whole.": 'ASC5_Average',
            "Sounds seemed to influence what I saw.": 'ASC6_Average',
            "I saw colours in complete darkness or with closed eyes.": 'ASC7_Average',
            "Shapes seemed to be changed by sounds or noises.": 'ASC8_Average',
            "My body seemed numb, lifeless, or alien.": 'ASC9_Average',
            "I was incapable of making even the slightest decision.": 'ASC10_Average',
            "Some unimportant things acquired special meaning.": 'ASC11_Average',
            "Things in my surroundings had a new or alien meaning.": 'ASC12_Average',
            "I was afraid of not being able to get out of the state in which I found myself.": 'ASC13_Average',
            "I saw brightness or flashes in complete darkness or with closed eyes.": 'ASC14_Average',
            "I felt one with my surroundings.": 'ASC15_Average',
            "I had difficulties in distinguishing important from non-important.": 'ASC16_Average',
            "I saw whole scenes in complete darkness or with closed eyes.": 'ASC17_Average',
            "I experienced a glimpse of eternity.": 'ASC18_Average',
            "Opposite and contradictions seemed to resolve.": 'ASC19_Average',
            "I was scared without knowing why.": 'ASC20_Average',
            "I experienced everything as frighteningly distorted.": 'ASC21_Average',
            "My surroundings appeared strange and eerie.": 'ASC22_Average',
            "I felt paralyzed.": 'ASC23_Average',
            "I felt particularly profound.": 'ASC24_Average',
            "I experienced past, present, and future as a unity.": 'ASC25_Average',
            "Objects in my surroundings touched me more emotionally.": 'ASC26_Average',
            "I felt threatened.": 'ASC27_Average',
            "I had the impression I was out of my body.": 'ASC28_Average',
            "I felt like I was floating.": 'ASC29_Average',
            "I felt isolated from everything and everyone.": 'ASC30_Average',
            "My thoughts were always interrupted; I could not think anything to its end.": 'ASC31_Average',
            "I had insights into the ways the world works that were mysterious to me before.": 'ASC32_Average',
            "I could see images from my memory or imagination with exceeding clarity.": 'ASC33_Average',
            "Colours seemed to be altered by sounds or noises.": 'ASC34_Average',
            "I had particularly inventive ideas.": 'ASC35_Average',
            "I had the impression of no longer having my own will.": 'ASC36_Average',
            "I felt full of awe.": 'ASC37_Average',
            "My imagination was extremely vivid.": 'ASC38_Average',
            "I experienced a profound inner peace.": 'ASC39_Average',
            "I had the feeling that something terrible was going to happen.": 'ASC40_Average',
            "I experienced all-embracing love.": 'ASC41_Average',
            "My experience had religious aspects.": 'ASC42_Average',
            "I felt a general sense of gratitude.": 'ASC43_Average',
            "I felt compassion towards others.": 'ASC44_Average',
            "I felt compassion towards myself.": 'ASC45_Average',
            "I felt a general sense of love.¬†": 'ASC46_Average',
            
        
            #MEQ
            "Freedom from the limitations of your personal self and feeling a unity or bond with what was felt to be greater than your personal self.": 'MEQ1_Average',
            "Experience of pure being and pure awareness (beyond the world of sense impressions).": 'MEQ2_Average',
            'Experience of oneness in relation to an "inner world" within.': 'MEQ3_Average',
            "Experience of the fusion of your personal self into a larger whole.": 'MEQ4_Average',
            "Experience of unity with ultimate reality.": 'MEQ5_Average',
            "Feeling that you experienced eternity or infinity.": 'MEQ6_Average',
            "Experience of oneness or unity with objects and/or persons perceived in your surroundings.": 'MEQ7_Average',
            'Experience of the insight that "all is One".': 'MEQ8_Average',
            "Awareness of the life or living presence in all things.": 'MEQ9_Average',
            "Gain of insightful knowledge experienced at an intuitive level.": 'MEQ10_Average',
            'Certainty of encounter with ultimately reality (in sense of being able to "know" and "see" what is really real at some point during your experience).': 'MEQ11_Average',
            'You are convinced now, as you look back on your experience, that in it you encountered ultimate reality (i.e. that you "knew" and "saw" what was really real).': 'MEQ12_Average',
            "Sense of being at a spiritual height.": 'MEQ13_Average',
            "Sense of Reverence.": 'MEQ14_Average',
            "Feeling that you experienced something profoundly sacred and holy.": 'MEQ15_Average',
            "Experience of amazement.": 'MEQ16_Average',
            "Feelings of tenderness and gentleness.": 'MEQ17_Average',
            "Feelings of peace and tranquillity.": 'MEQ18_Average',
            "Experience of ecstasy.": 'MEQ19_Average',
            "Sense of awe or awesomeness.": 'MEQ20_Average',
            "Feelings of joy.": 'MEQ21_Average',
            "Loss of your usual sense of time.": 'MEQ22_Average',
            "Loss of your usual sense of space.": 'MEQ23_Average',
            "Loss of usual awareness of where you were.": 'MEQ24_Average',
            'Sense of being "outside of" time, beyond past and future.': 'MEQ25_Average',
            "Being in a realm with no space boundaries.": 'MEQ26_Average',
            "Experience of timelessness.": 'MEQ27_Average',
            "Sense that the experience cannot be described adequately in words.": 'MEQ28_Average',
            "Feeling that you could not do justice to your experience by describing it in words.": 'MEQ29_Average',
            "Feeling that it would be difficult to communicate your own experience to others who have not had similar experiences.": 'MEQ30_Average',
            
            #EDI
            'I experienced a dissolution of my "self" or ego.': 'EDI1_Average',
            "I felt at one with the universe.": 'EDI2_Average',
            "I felt a sense of union with others.": 'EDI3_Average',
            "I experienced a decrease in my sense of self-importance.": 'EDI4_Average',
            'I experienced a disintegration of my "self" or ego.': 'EDI5_Average',
            "I felt far less absorbed by my own issues and concerns.": 'EDI6_Average',
            "I lost all sense of ego.": 'EDI7_Average',
            "all notion of self and identity dissolved away.": 'EDI8_Average',
                   
    
            #EBI
            "I faced emotionally difficult feelings that I usually push aside.": 'EBI1_Average',
            "I experienced a resolution of a personal conflict/trauma": 'EBI2_Average',
            "I felt able to explore challenging emotions and memories.": 'EBI3_Average',
            "I was resisting and avoiding challenging feelings throughout, without breakthrough.": 'EBI4_Average',
            "I had an emotional breakthrough.¬†": 'EBI5_Average',
            "I was able to get a sense of closure on an emotional problem.": 'EBI6_Average',
            "I felt emotionally stuck throughout, without breakthrough.": 'EBI7_Average',
            "I achieved an emotional release followed by a sense of relief.": 'EBI8_Average',
            
            #CEQ
            "Isolation and loneliness": 'CEQ1_Average',
            "Sadness": 'CEQ2_Average',
            "Feeling my heart beating": 'CEQ3_Average',
            "I had the feeling something horrible would happen": 'CEQ4_Average',
            "Feeling my body shake/tremble": 'CEQ5_Average',
            "Feelings of grief": 'CEQ6_Average',
            "Experience of fear": 'CEQ7_Average',
            "Fear that I might lose my mind or go insane": 'CEQ8_Average',
            "I felt like crying": 'CEQ9_Average',
            "Feeling of isolation from people and things": 'CEQ10_Average',
            "Feelings of despair": 'CEQ11_Average',
            "I had the feeling that people were plotting against me": 'CEQ12_Average',
            "I was afraid that the state I was in would last forever": 'CEQ13_Average',
            "Anxiousness": 'CEQ14_Average',
            "I felt shaky inside": 'CEQ15_Average',
            "I had the profound experience of my own death": 'CEQ16_Average',
            "I felt my heart beating irregularly or skipping beats¬†": 'CEQ17_Average',
            "Pressure or weight in my chest or abdomen": 'CEQ18_Average',
            "I experienced a decreased sense of sanity¬†": 'CEQ19_Average',
            "I felt as if I was dead or dying": 'CEQ20_Average',
            "Panic": 'CEQ21_Average',
            "Experience of antagonism toward people around me": 'CEQ22_Average',
            "Despair": 'CEQ23_Average',
            "I felt isolated from everything and everyone": 'CEQ24_Average',
            "Emotional and/or physical suffering": 'CEQ25_Average',
            "I felt frightened": 'CEQ26_Average',
            
            
            # Acute SE for Cohort 1
            "An upset stomach or nausea:Have you experienced any of the following symptoms since your psychedelic experience?": 'nausea',
            "Trouble sleeping:Have you experienced any of the following symptoms since your psychedelic experience?": 'Trouble sleeping',
            "Headache:Have you experienced any of the following symptoms since your psychedelic experience?": 'Headache',
            "Acid indigestion or heartburn:Have you experienced any of the following symptoms since your psychedelic experience?": 'Acid indigestion or heartbur',
            "Eye strain:Have you experienced any of the following symptoms since your psychedelic experience?": 'Eye strain',
            "Diarrhea:Have you experienced any of the following symptoms since your psychedelic experience?": 'Diarrhea',
            "Stomach cramps (not menstrual):Have you experienced any of the following symptoms since your psychedelic experience?": 'Stomach cramps',
            "Constipation:Have you experienced any of the following symptoms since your psychedelic experience?": 'Constipation',
            "Ringing in the ears:Have you experienced any of the following symptoms since your psychedelic experience?": 'Ringing in the ears',
            "Loss of appetite:Have you experienced any of the following symptoms since your psychedelic experience?": 'Loss of appetite',
            "Dizziness:Have you experienced any of the following symptoms since your psychedelic experience?": 'Dizziness',
            "Tiredness or fatigue:Have you experienced any of the following symptoms since your psychedelic experience?": 'Tiredness or fatigue'}))

#### Post

In [6]:
# Renaming columns names for cohort 1 post-experience

c1_post = (c1_post.rename(columns={"URL Variable: sguid": 'URL',
                                   'City':'City_post',
                                   'Country':'Country_post',
                                    'Response ID':'ID_post',
                                    "I've been feeling optimistic about the future.": 'WEMWBS1_post',
                                    "I've been feeling useful.": 'WEMWBS2_post',
                                    "I've been feeling relaxed.": 'WEMWBS3_post',
                                    "I've been feeling interested in other people.¬†": 'WEMWBS4_post',
                                    "I've had energy to spare.": 'WEMWBS5_post',
                                    "I've been dealing with problems well.¬†": 'WEMWBS6_post',
                                    "I've been thinking clearly.": 'WEMWBS7_post',
                                    "I've been feeling good about myself.¬†": 'WEMWBS8_post',
                                    "I've been feeling close to other people.¬†": 'WEMWBS9_post',
                                    "I've been feeling confident.": 'WEMWBS10_post',
                                    "I've been able to make up my own mind about things.¬†": 'WEMWBS11_post',
                                    "I've been feeling loved.¬†": 'WEMWBS12_post',
                                    "I've been interested in new things.¬†": 'WEMWBS13_post',
                                    "I've been feeling cheerful.¬†": 'WEMWBS14_post'}))

### Cohort 2

#### Baseline

In [7]:
c2_baseline = (c2_baseline.rename(columns={
            'URL Variable: sguid': 'URL',
            "Response ID": 'ID_baseline',
            "Country": 'Country_baseline',
            'City':'City_baseline',   
            "Your age:": 'age',
            "Your gender:": 'gender',
            "Nationality (e.g. GB = British; US = USA):": 'nationality',
            "Highest educational level attained:": 'education',
            "Employment:": 'Employment',
            "LSD:Please indicate what psychedelics you have used in the past. ¬†": 'LSD use',
            "DMT:Please indicate what psychedelics you have used in the past. ¬†": 'DMT use',
            "Ayahuasca:Please indicate what psychedelics you have used in the past. ¬†": 'Ayahuasca use',
            "Psilocybin / magic mushrooms / truffles:Please indicate what psychedelics you have used in the past. ¬†": 'psychedelics use',
            "Mescaline (Peyote, San Pedro):Please indicate what psychedelics you have used in the past. ¬†": 'Mescaline use',
            "Salvia Divinorum:Please indicate what psychedelics you have used in the past. ¬†": 'Salvia Divinorum use',
            "Iboga / Ibogaine:Please indicate what psychedelics you have used in the past. ¬†": 'Iboga use',
            "Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, 2C-B, 4-ACO-DMT, 1P-LSD):Please indicate what psychedelics you have used in the past. ¬†": 'Hallucinogen use',
            "Other - Write In:Please indicate what psychedelics you have used in the past. ¬†": 'Other use',
            "None of the above:Please indicate what psychedelics you have used in the past. ¬†": 'None psychedelics use',
            "Other - Write In:Please indicate what psychedelics you have used in the past. ¬†.1": 'other1 use',
            "Please indicate the number of times you have taken classic psychedelic substances (LSD, psilocybin, DMT, ayahuasca, mescaline).": 'number of times you have taken psychedelic',
            "Amphetamines:Please indicate what other drugs you have used at least once.": 'Amphetamines use',
            "MDMA/Ecstasy:Please indicate what other drugs you have used at least once.": 'MDMA/Ecstasy use',
            "Cocaine:Please indicate what other drugs you have used at least once.": 'Cocaine use',
            "Opiates:Please indicate what other drugs you have used at least once.": 'Opiates use',
            "Benzodiazepines:Please indicate what other drugs you have used at least once.": 'Benzodiazepines use',
            "Ketamine:Please indicate what other drugs you have used at least once.": 'Ketamine use',
            "None of the above:Please indicate what other drugs you have used at least once.": 'None drugs use',
            
            "Major depressive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Major depressive disorder',
            "Bipolar disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Bipolar disorder',
            "Schizophrenia:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Schizophrenia',
            "Anxiety disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Anxiety disorder',
            "Substance abuse disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Substance abuse disorder',
            "Alcohol dependence:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Alcohol dependence',
            "Hallucinogen persisting perception disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Hallucinogen persisting perception disorder',
            "Psychotic disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Psychotic disorder',
            "Personality disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Personality disorder',
            "ADHD:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'ADHD',
            "Obsessive compulsive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Obsessive compulsive disorder',
            "Eating disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Eating disorder',
            "None of the above:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'No disorder',
           
            "Have you ever been treated with medication(s) for the illness(es) stated above?": 'treated with medications',
            "Are you currently using this/these medication(s)?": 'Current use',
            "Anti-depressants:What is your current prescribed medication?": 'Anti-depressants',
            "Mood stabilisers:What is your current prescribed medication?": 'Mood stabilisers',
            "Anti-psychotics:What is your current prescribed medication?": 'Anti-psychotics',
            "ADHD medication:What is your current prescribed medication?": 'ADHD medication',
            "Medication for substance abuse disorder:What is your current prescribed medication?": 'substance abuse disorder meds',
            "Medication for alcohol dependence:What is your current prescribed medication?": 'alcohol dependence meds',
            "None of the above:What is your current prescribed medication?": 'No current meds',
            "For how long have you been using prescribed anti-depressants?": 'how long',
            "Are you planning to stop or pause taking the prescribed medication for your planned psychedelic experience?": 'plan to continue antidepressants',
        
            "What type of compound do you anticipate to take in your upcoming experience?": 'compound to take',
            "Other - Write In:What type of compound do you anticipate to take in your upcoming experience?": 'other compound',
            "Fun / recreational / party:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Fun / recreational / party',
            "Spiritual healing:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'spiritual healing',
            "Treatment of mental health problems:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Treatment of mental health problems',
            "Healing of physical illness:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Healing physical illness',
            "Religious practice:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Religious practice',
            "Curiosity:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Curiosity',
            "Social:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Social',
            "Connection with nature:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Connection with nature',
            "Communication with the spirit world:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'Communication with the spirit world',
            "To escape from difficult emotions:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'escape from difficult emotions',
            "To confront difficult emotions:Can you indicate what your motives are to undergo a psychedelic ceremony?": 'confront difficult emotions',
            

            #Not in Cohort 1 but in 2
            "White:Ethnic Group (Check one or more):": 'White',
            "Black or African American:Ethnic Group (Check one or more):": 'Black or African American',
            "Asian:Ethnic Group (Check one or more):": 'Asian',
            "American Indian or Alaskan Native:Ethnic Group (Check one or more):": 'American Indian or Alaskan Native',
            "Native Hawaiian or Other Pacific Islander:Ethnic Group (Check one or more):": 'Native Hawaiian or Other Pacific Islander',
            "Unknown:Ethnic Group (Check one or more):": 'Unknown',
            "Prefer not to say:Ethnic Group (Check one or more):": 'Not say',

    
            #Baseline Well-being
            "I've been feeling optimistic about the future.": 'WEMWBS1_baseline',
            "I've been feeling useful.": 'WEMWBS2_baseline',
            "I've been feeling relaxed.": 'WEMWBS3_baseline',
            "I've been feeling interested in other people.¬†": 'WEMWBS4_baseline',
            "I've had energy to spare.": 'WEMWBS5_baseline',
            "I've been dealing with problems well.¬†": 'WEMWBS6_baseline',
            "I've been thinking clearly.": 'WEMWBS7_baseline',
            "I've been feeling good about myself.¬†": 'WEMWBS8_baseline',
            "I've been feeling close to other people.¬†": 'WEMWBS9_baseline',
            "I've been feeling confident.": 'WEMWBS10_baseline',
            "I've been able to make up my own mind about things.¬†": 'WEMWBS11_baseline',
            "I've been feeling loved.¬†": 'WEMWBS12_baseline',
            "I am interested in new things.¬†": 'WEMWBS13_baseline',
            "I've been feeling cheerful.¬†": 'WEMWBS14_baseline'}))

#### Acute

In [8]:
c2_acute = (c2_acute.rename(columns={
            "URL Variable: sguid": 'URL',
            "City": "City_acute",
            "Country": 'Country_acute',                        
            "Response ID": 'ID_acute',
            "Which substance did you use in the psychedelic session/experience?": 'used substance',
            "Other - Write In:Which substance did you use in the psychedelic session/experience?": 'other substance',
            "How did you administer the drug": 'rote of administration',
            "Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†',": 'total dose',
            "If you know the exact dose you may write it here: (please also remind us what drug you are referring to) ¬†": 'exact dose',
            "Cannabis:Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Cannabis',
            "Alcohol:Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Alcohol',
            "Stimulants (e.g. amphetamines, cocaine):Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Stimulants',
            "Tobacco:Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'Tobacco',
            "MDMA/ecstasy:Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'MDMA/ecstasy',
            "Opioids:Please indicate what other types of drugs (incl. the dose) you used during your psychedelic experience?": 'opiods',
    
            #Acute Questionnaires
            
            #ASC for cohort 2 (differetn questionnaire for Cohorts)
            "I saw regular patterns in complete darkness or with closed eyes.": 'ASC46_Average', #this is ASC 4 for cohort 1
            "I saw colours before me in total darkness or with closed eyes.": 'ASC47_Average',
            "I saw lights or flashes of light in total darkness or with closed eyes.": 'ASC48_Average',
            "I saw scenes rolling by in total darkness or with my eyes closed.": 'ASC49_Average',
            "My imagination was extremely vivid.¬†": 'ASC50_Average',
            "I could see pictures from my past or fantasy extremely clearly": 'ASC51_Average',
            "Noises seemed to influence what I saw": 'ASC52_Average',
            "The shapes of things seemed to change by sounds and noises": 'ASC53_Average',
            "The colors of things seemed to be changed by sounds and noises": 'ASC54_Average',
            
            #MEQ
            "Freedom from the limitations of your personal self and feeling a unity or bond with what was felt to be greater than your personal self.": 'MEQ1_Average',
            "Experience of pure being and pure awareness (beyond the world of sense impressions).": 'MEQ2_Average',
            'Experience of oneness in relation to an "inner world" within.': 'MEQ3_Average',
            "Experience of the fusion of your personal self into a larger whole.": 'MEQ4_Average',
            "Experience of unity with ultimate reality.": 'MEQ5_Average',
            "Feeling that you experienced eternity or infinity.": 'MEQ6_Average',
            "Experience of oneness or unity with objects and/or persons perceived in your surroundings.": 'MEQ7_Average',
            'Experience of the insight that "all is One".': 'MEQ8_Average',
            "Awareness of the life or living presence in all things.": 'MEQ9_Average',
            "Gain of insightful knowledge experienced at an intuitive level.": 'MEQ10_Average',
            'Certainty of encounter with ultimately reality (in sense of being able to "know" and "see" what is really real at some point during your experience).': 'MEQ11_Average',
            'You are convinced now, as you look back on your experience, that in it you encountered ultimate reality (i.e. that you "knew" and "saw" what was really real).': 'MEQ12_Average',
            "Sense of being at a spiritual height.": 'MEQ13_Average',
            "Sense of Reverence.": 'MEQ14_Average',
            "Feeling that you experienced something profoundly sacred and holy.": 'MEQ15_Average',
            "Experience of amazement.": 'MEQ16_Average',
            "Feelings of tenderness and gentleness.": 'MEQ17_Average',
            "Feelings of peace and tranquillity.": 'MEQ18_Average',
            "Experience of ecstasy.": 'MEQ19_Average',
            "Sense of awe or awesomeness.": 'MEQ20_Average',
            "Feelings of joy.": 'MEQ21_Average',
            "Loss of your usual sense of time.": 'MEQ22_Average',
            "Loss of your usual sense of space.": 'MEQ23_Average',
            "Loss of usual awareness of where you were.": 'MEQ24_Average',
            'Sense of being "outside of" time, beyond past and future.': 'MEQ25_Average',
            "Being in a realm with no space boundaries.": 'MEQ26_Average',
            "Experience of timelessness.": 'MEQ27_Average',
            "Sense that the experience cannot be described adequately in words.": 'MEQ28_Average',
            "Feeling that you could not do justice to your experience by describing it in words.": 'MEQ29_Average',
            "Feeling that it would be difficult to communicate your own experience to others who have not had similar experiences.": 'MEQ30_Average',
            
            #EDI
            'I experienced a dissolution of my "self" or ego.': 'EDI1_Average',
            "I felt at one with the universe.": 'EDI2_Average',
            "I felt a sense of union with others.": 'EDI3_Average',
            "I experienced a decrease in my sense of self-importance.": 'EDI4_Average',
            'I experienced a disintegration of my "self" or ego.': 'EDI5_Average',
            "I felt far less absorbed by my own issues and concerns.": 'EDI6_Average',
            "I lost all sense of ego.": 'EDI7_Average',
            "all notion of self and identity dissolved away.": 'EDI8_Average',
                   
            #EDI for cohort 2 additional questions 
            "I felt especially assertive¬†": 'EDI9_Average',
            "I felt more important or special than others": 'EDI10_Average',
            "My ego felt inflated": 'EDI11_Average',
            "I felt especially sure-of-myself¬†": 'EDI12_Average',
            "I felt especially keen and competitive": 'EDI13_Average',
            "I felt like my viewpoint was worth more than other peoples'": 'EDI14_Average',
            "I felt especially self-confident": 'EDI15_Average',
            "I felt especially self-assured": 'EDI16_Average',
            "All notion of self and identity dissolved away.": 'EDI17_Average',
            
            #EBI
            "I faced emotionally difficult feelings that I usually push aside.": 'EBI1_Average',
            "I experienced a resolution of a personal conflict/trauma": 'EBI2_Average',
            "I felt able to explore challenging emotions and memories.": 'EBI3_Average',
            "I was resisting and avoiding challenging feelings throughout, without breakthrough.": 'EBI4_Average',
            "I had an emotional breakthrough.¬†": 'EBI5_Average',
            "I was able to get a sense of closure on an emotional problem.": 'EBI6_Average',
            "I felt emotionally stuck throughout, without breakthrough.": 'EBI7_Average',
            "I achieved an emotional release followed by a sense of relief.": 'EBI8_Average',
            
            #CEQ
            "Isolation and loneliness": 'CEQ1_Average',
            "Sadness": 'CEQ2_Average',
            "Feeling my heart beating": 'CEQ3_Average',
            "I had the feeling something horrible would happen": 'CEQ4_Average',
            "Feeling my body shake/tremble": 'CEQ5_Average',
            "Feelings of grief": 'CEQ6_Average',
            "Experience of fear": 'CEQ7_Average',
            "Fear that I might lose my mind or go insane": 'CEQ8_Average',
            "I felt like crying": 'CEQ9_Average',
            "Feeling of isolation from people and things": 'CEQ10_Average',
            "Feelings of despair": 'CEQ11_Average',
            "I had the feeling that people were plotting against me": 'CEQ12_Average',
            "I was afraid that the state I was in would last forever": 'CEQ13_Average',
            "Anxiousness": 'CEQ14_Average',
            "I felt shaky inside": 'CEQ15_Average',
            "I had the profound experience of my own death": 'CEQ16_Average',
            "I felt my heart beating irregularly or skipping beats¬†": 'CEQ17_Average',
            "Pressure or weight in my chest or abdomen": 'CEQ18_Average',
            "I experienced a decreased sense of sanity¬†": 'CEQ19_Average',
            "I felt as if I was dead or dying": 'CEQ20_Average',
            "Panic": 'CEQ21_Average',
            "Experience of antagonism toward people around me": 'CEQ22_Average',
            "Despair": 'CEQ23_Average',
            "I felt isolated from everything and everyone": 'CEQ24_Average',
            "Emotional and/or physical suffering": 'CEQ25_Average',
            "I felt frightened": 'CEQ26_Average',
            
            
            #Acute SE for Cohort 2
            "Nausea or vomiting:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'nausea',
            "Gut changes (e.g. diarrhea):Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Diarrhea',
            "Body aches:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Body aches',
            "Ringing in the ears:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Ringing in the ears',
            "Headache:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Headache',
            "Sweats or chills:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Sweats or chills',
            "Crying:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Crying',
            "Feeling hot or cold:Have you experienced any of the following during the psychedelic experience/session? Please tick the respective box(es).": 'Feeling hot or cold'}))

#### Post

In [9]:
c2_post = (c2_post.rename(columns={
            "URL Variable: sguid": 'URL',
            'City':'City_post',
            'Country':'Country_post',
            'Response ID':'ID_post',
             "I've been feeling optimistic about the future.": 'WEMWBS1_post',
            "I've been feeling useful.": 'WEMWBS2_post',
            "I've been feeling relaxed.": 'WEMWBS3_post',
            "I've been feeling interested in other people.¬†": 'WEMWBS4_post',
            "I've had energy to spare.": 'WEMWBS5_post',
            "I've been dealing with problems well.¬†": 'WEMWBS6_post',
            "I've been thinking clearly.": 'WEMWBS7_post',
            "I've been feeling good about myself.¬†": 'WEMWBS8_post',
            "I've been feeling close to other people.¬†": 'WEMWBS9_post',
            "I've been feeling confident.": 'WEMWBS10_post',
            "I've been able to make up my own mind about things.¬†": 'WEMWBS11_post',
            "I've been feeling loved.¬†": 'WEMWBS12_post',
            "I am interested in new things.¬†": 'WEMWBS13_post',
            "I've been feeling cheerful.¬†": 'WEMWBS14_post'}))

# Merging the datasets (before column selection)

In [10]:
# First let's merge cohort 1 and cohort 2 data because these datasets 
# have more similar timepoints than ceremony study. 

# The concat function is a clever function which allows joining 
# different dataframes into 1. The phrase "axis = 0" tells the 
# function to merge the dataframes vertically (i.e., add more rows). 

baseline = pd.concat([c1_baseline, c2_baseline], axis=0)
acute = pd.concat([c1_acute, c2_acute], axis=0)
post = pd.concat([c1_post, c2_post], axis=0)

In [11]:
# First let's merge cohort 1 and cohort 2 data because these datasets 
# have more similar timepoints than ceremony study. 

# The concat function is a clever function which allows joining 
# different dataframes into 1. The phrase "axis = 0" tells the 
# function to merge the dataframes vertically (i.e., add more rows). 

baseline = pd.concat([c1_baseline, c2_baseline], axis=0)
acute = pd.concat([c1_acute, c2_acute], axis=0)
post = pd.concat([c1_post, c2_post], axis=0)

# Here we once again use the concat function, but through specifying that 
# "axis = 1" we tell the function that we want to merge the data frames 
# horizontally, i.e. add more columns.

c1_c2 = pd.concat([baseline, acute, post], axis=1)
c1_c2

# We might also want to have data frames which contain all of the cohort 1
# and cohort 2 data separately. This may or may not be useful, 
# but good to have it just in case

c1 = pd.concat([c1_baseline, c1_acute, c1_post], axis=1)
c2 = pd.concat([c2_baseline, c2_acute, c2_post], axis=1)

# Selecting relevant columns for final analysis

## Cohort 1

In [12]:
#With this code we are trying to drop the columns that we do not want from the excel file 
#We only add the column we want

c1_new = (c1[[
                 'ID_baseline',
                 'Country_baseline',
                 'City_baseline',
                 'age',
                 'gender',
                 'nationality',
                 'education',
                 'Employment',
                 'LSD use',
                 'DMT use',
                 'Ayahuasca use',
                 'psychedelics use',
                 'Mescaline use',
                 'Salvia Divinorum use',
                 'Iboga use',
                 'Hallucinogen use',
                 'Other use',
                 'None psychedelics use',
                 'other1 use',
                 'number of times you have taken psychedelic',
                 'Amphetamines use',
                 'MDMA/Ecstasy use',
                 'Cocaine use',
                 'Opiates use',
                 'Benzodiazepines use',
                 'Ketamine use',
                 'None drugs use',
                 'Major depressive disorder',
                 'Bipolar disorder',
                 'Schizophrenia',
                 'Anxiety disorder',
                 'Substance abuse disorder',
                 'Alcohol dependence',
                 'Hallucinogen persisting perception disorder',
                 'Psychotic disorder',
                 'Personality disorder',
                 'ADHD',
                 'Obsessive compulsive disorder',
                 'Eating disorder',
                 'No disorder',
                 'treated with medications',
                 'Current use',
                 'Anti-depressants',
                 'Mood stabilisers',
                 'Anti-psychotics',
                 'ADHD medication',
                 'substance abuse disorder meds',
                 'alcohol dependence meds',
                 'No current meds',
                 'compound to take',
                 'other compound',
                 'Fun / recreational / party',
                 'Therapeutic / personal growth',
                 'Medicinal',
                 'Spiritual experience',
                 'Religious practice',
                 'Curiosity',
                 'Social',
                 'Connection with nature',
                 'escape from difficult emotions',
                 'confront difficult emotions',
                 'WEMWBS1_baseline',
                 'WEMWBS2_baseline',
                 'WEMWBS3_baseline',
                 'WEMWBS4_baseline',
                 'WEMWBS5_baseline',
                 'WEMWBS6_baseline',
                 'WEMWBS7_baseline',
                 'WEMWBS8_baseline',
                 'WEMWBS9_baseline',
                 'WEMWBS10_baseline',
                 'WEMWBS11_baseline',
                 'WEMWBS12_baseline',
                 'WEMWBS13_baseline',
                 'WEMWBS14_baseline',
                 'ID_acute',
                 'Country_acute',
                 'used substance',
                 'other substance',
                 'rote of administration',
                 'Other - Write In:How did you administer the drug/medicine?',
                 'total dose',
                 'exact dose',
                 'Cannabis',
                 'Alcohol',
                 'Stimulants',
                 'Tobacco',
                 'MDMA/ecstasy',
                 'ASC1_Average',
                 'ASC2_Average',
                 'ASC3_Average',
                 'ASC4_Average',
                 'ASC5_Average',
                 'ASC6_Average',
                 'ASC7_Average',
                 'ASC8_Average',
                 'ASC9_Average',
                 'ASC10_Average',
                 'ASC11_Average',
                 'ASC12_Average',
                 'ASC13_Average',
                 'ASC14_Average',
                 'ASC15_Average',
                 'ASC16_Average',
                 'ASC17_Average',
                 'ASC18_Average',
                 'ASC19_Average',
                 'ASC20_Average',
                 'ASC21_Average',
                 'ASC22_Average',
                 'ASC23_Average',
                 'ASC24_Average',
                 'ASC25_Average',
                 'ASC26_Average',
                 'ASC27_Average',
                 'ASC28_Average',
                 'ASC29_Average',
                 'ASC30_Average',
                 'ASC31_Average',
                 'ASC32_Average',
                 'ASC33_Average',
                 'ASC34_Average',
                 'ASC35_Average',
                 'ASC36_Average',
                 'ASC37_Average',
                 'ASC38_Average',
                 'ASC39_Average',
                 'ASC40_Average',
                 'ASC41_Average',
                 'ASC42_Average',
                 'ASC43_Average',
                 'ASC44_Average',
                 'ASC45_Average',
                'ASC46_Average',
                 'MEQ1_Average',
                 'MEQ2_Average',
                 'MEQ3_Average',
                 'MEQ4_Average',
                 'MEQ5_Average',
                 'MEQ6_Average',
                 'MEQ7_Average',
                 'MEQ8_Average',
                 'MEQ9_Average',
                 'MEQ10_Average',
                 'MEQ11_Average',
                 'MEQ12_Average',
                 'MEQ13_Average',
                 'MEQ14_Average',
                 'MEQ15_Average',
                 'MEQ16_Average',
                 'MEQ17_Average',
                 'MEQ18_Average',
                 'MEQ19_Average',
                 'MEQ20_Average',
                 'MEQ21_Average',
                 'MEQ22_Average',
                 'MEQ23_Average',
                 'MEQ24_Average',
                 'MEQ25_Average',
                 'MEQ26_Average',
                 'MEQ27_Average',
                 'MEQ28_Average',
                 'MEQ29_Average',
                 'MEQ30_Average',
                 'nausea',
                 'Trouble sleeping',
                 'Headache',
                 'Acid indigestion or heartbur',
                 'Eye strain',
                 'Diarrhea',
                 'Stomach cramps',
                 'Constipation',
                 'Ringing in the ears',
                 'Loss of appetite',
                 'Dizziness',
                 'Tiredness or fatigue',
                 'EDI1_Average',
                 'EDI2_Average',
                 'EDI3_Average',
                 'EDI4_Average',
                 'EDI5_Average',
                 'EDI6_Average',
                 'EDI7_Average',
                 'EDI8_Average',
                 'EBI1_Average',
                 'EBI2_Average',
                 'EBI3_Average',
                 'EBI4_Average',
                 'EBI5_Average',
                 'EBI6_Average',
                 'EBI7_Average',
                 'EBI8_Average',
                 'CEQ1_Average',
                 'CEQ2_Average',
                 'CEQ3_Average',
                 'CEQ4_Average',
                 'CEQ5_Average',
                 'CEQ6_Average',
                 'CEQ7_Average',
                 'CEQ8_Average',
                 'CEQ9_Average',
                 'CEQ10_Average',
                 'CEQ11_Average',
                 'CEQ12_Average',
                 'CEQ13_Average',
                 'CEQ14_Average',
                 'CEQ15_Average',
                 'CEQ16_Average',
                 'CEQ17_Average',
                 'CEQ18_Average',
                 'CEQ19_Average',
                 'CEQ20_Average',
                 'CEQ21_Average',
                 'CEQ22_Average',
                 'CEQ23_Average',
                 'CEQ24_Average',
                 'CEQ25_Average',
                 'CEQ26_Average',
                 'ID_post',
                 'Country_post',
                 'City_post',
                 'State/Region',
                 'Postal',
                 'URL Variable: date',
                 'URL Variable: email',
                 'WEMWBS1_post',
                 'WEMWBS2_post',
                 'WEMWBS3_post',
                 'WEMWBS4_post',
                 'WEMWBS5_post',
                 'WEMWBS6_post',
                 'WEMWBS7_post',
                 'WEMWBS8_post',
                 'WEMWBS9_post',
                 'WEMWBS10_post',
                 'WEMWBS11_post',
                 'WEMWBS12_post',
                 'WEMWBS13_post',
                 'WEMWBS14_post'
                ]])

## Cohort 2

In [13]:
c2_new = (c2[['ID_baseline',
              'ID_acute',
              'ID_post',
              'Country_baseline',
              'Country_acute',
              'Country_post',
                 'age',
                 'gender',
                 'nationality',
                 'White',
                 'Black or African American',
                 'Asian',
                 'American Indian or Alaskan Native',
                 'Native Hawaiian or Other Pacific Islander',
                 'Unknown',
                 'Not say',
                 'education',
                 'Employment',
                 'LSD use',
                 'DMT use',
                 'Ayahuasca use',
                 'psychedelics use',
                 'Mescaline use',
                 'Salvia Divinorum use',
                 'Iboga use',
                 'Hallucinogen use',
                 'Other use',
                 'None psychedelics use',
                 'other1 use',
                 'number of times you have taken psychedelic',
                 'Amphetamines use',
                 'MDMA/Ecstasy use',
                 'Cocaine use',
                 'Opiates use',
                 'Benzodiazepines use',
                 'Ketamine use',
                 'None drugs use',
                 'Major depressive disorder',
                 'Bipolar disorder',
                 'Schizophrenia',
                 'Anxiety disorder',
                 'Substance abuse disorder',
                 'Alcohol dependence',
                 'Hallucinogen persisting perception disorder',
                 'Psychotic disorder',
                 'Personality disorder',
                 'ADHD',
                 'Obsessive compulsive disorder',
                 'Eating disorder',
                 'No disorder',
                 'Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, antipsychotics, ADHD medication, mood stabilisers)?',
                 'Current use',
                 'Anti-depressants',
                 'Mood stabilisers',
                 'Anti-psychotics',
                 'ADHD medication',
                 'substance abuse disorder meds',
                 'alcohol dependence meds',
                 'No current meds',
                 'Fluoxetine:What is your currently prescribed anti-depressant? Please tick',
                 'Citalopram:What is your currently prescribed anti-depressant? Please tick',
                 'Sertraline:What is your currently prescribed anti-depressant? Please tick',
                 'Paroxetine:What is your currently prescribed anti-depressant? Please tick',
                 'Escitalopram:What is your currently prescribed anti-depressant? Please tick',
                 'Venlafaxine:What is your currently prescribed anti-depressant? Please tick',
                 'Duloxetine:What is your currently prescribed anti-depressant? Please tick',
                 'Trazadone:What is your currently prescribed anti-depressant? Please tick',
                 'Mirtazapine:What is your currently prescribed anti-depressant? Please tick',
                 'Other - Write In:What is your currently prescribed anti-depressant? Please tick',
                 'Other - Write In:What is your currently prescribed anti-depressant? Please tick.1',
                 'how long',
                 'plan to continue antidepressants',
                 'compound to take',
                 'other compound',
                 'Fun / recreational / party',
                 'spiritual healing',
                 'Treatment of mental health problems',
                 'Healing physical illness',
                 'Spiritual experience:Can you indicate what your motives are to undergo a psychedelic ceremony?',
                 'Religious practice',
                 'Curiosity',
                 'Social',
                 'Connection with nature',
                 'Communication with the spirit world',
                 'escape from difficult emotions',
                 'confront difficult emotions',
                 'WEMWBS1_baseline',
                 'WEMWBS2_baseline',
                 'WEMWBS3_baseline',
                 'WEMWBS4_baseline',
                 'WEMWBS5_baseline',
                 'WEMWBS6_baseline',
                 'WEMWBS7_baseline',
                 'WEMWBS8_baseline',
                 'WEMWBS9_baseline',
                 'WEMWBS10_baseline',
                 'WEMWBS11_baseline',
                 'WEMWBS12_baseline',
                 'WEMWBS13_baseline',
                 'WEMWBS14_baseline',
                 'used substance',
                 'other substance',
                 'How did you administer the drug?',
                 'Other - Write In:How did you administer the drug?',
                 'Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†',
                 'exact dose',
                 'How intense would you rate your psychedelic drug experience?',
                 'Cannabis',
                 'Alcohol',
                 'Stimulants',
                 'Tobacco',
                 'MDMA/ecstasy',
                 'opiods',
                 'ASC46_Average',
                 'ASC47_Average',
                 'ASC48_Average',
                 'ASC49_Average',
                 'ASC50_Average',
                 'ASC51_Average',
                 'ASC52_Average',
                 'ASC53_Average',
                 'ASC54_Average',
                 'MEQ1_Average',
                 'MEQ2_Average',
                 'MEQ3_Average',
                 'MEQ4_Average',
                 'MEQ5_Average',
                 'MEQ6_Average',
                 'MEQ7_Average',
                 'MEQ8_Average',
                 'MEQ9_Average',
                 'MEQ10_Average',
                 'MEQ11_Average',
                 'MEQ12_Average',
                 'MEQ13_Average',
                 'MEQ14_Average',
                 'MEQ15_Average',
                 'MEQ16_Average',
                 'MEQ17_Average',
                 'MEQ18_Average',
                 'MEQ19_Average',
                 'MEQ20_Average',
                 'MEQ21_Average',
                 'MEQ22_Average',
                 'MEQ23_Average',
                 'MEQ24_Average',
                 'MEQ25_Average',
                 'MEQ26_Average',
                 'MEQ27_Average',
                 'MEQ28_Average',
                 'MEQ29_Average',
                 'MEQ30_Average',
                 'EDI9_Average',
                 'EDI1_Average',
                 'EDI10_Average',
                 'EDI2_Average',
                 'EDI11_Average',
                 'EDI3_Average',
                 'EDI12_Average',
                 'EDI4_Average',
                 'EDI13_Average',
                 'EDI5_Average',
                 'EDI14_Average',
                 'EDI6_Average',
                 'EDI15_Average',
                 'EDI7_Average',
                 'EDI16_Average',
                 'EDI17_Average',
                 'EBI1_Average',
                 'EBI2_Average',
                 'EBI3_Average',
                 'EBI4_Average',
                 'EBI5_Average',
                 'EBI6_Average',
                 'EBI7_Average',
                 'EBI8_Average',
                 'CEQ1_Average',
                 'CEQ2_Average',
                 'CEQ3_Average',
                 'CEQ4_Average',
                 'CEQ5_Average',
                 'CEQ6_Average',
                 'CEQ7_Average',
                 'CEQ8_Average',
                 'CEQ9_Average',
                 'CEQ10_Average',
                 'CEQ11_Average',
                 'CEQ12_Average',
                 'CEQ13_Average',
                 'CEQ14_Average',
                 'CEQ15_Average',
                 'CEQ16_Average',
                 'CEQ17_Average',
                 'CEQ18_Average',
                 'CEQ19_Average',
                 'CEQ20_Average',
                 'CEQ21_Average',
                 'CEQ22_Average',
                 'CEQ23_Average',
                 'CEQ24_Average',
                 'CEQ25_Average',
                 'CEQ26_Average',
                 'nausea',
                 'Diarrhea',
                 'Body aches',
                 'Ringing in the ears',
                 'Headache',
                 'Sweats or chills',
                 'Crying',
                 'Feeling hot or cold',
                 'WEMWBS1_post',
                 'WEMWBS2_post',
                 'WEMWBS3_post',
                 'WEMWBS4_post',
                 'WEMWBS5_post',
                 'WEMWBS6_post',
                 'WEMWBS7_post',
                 'WEMWBS8_post',
                 'WEMWBS9_post',
                 'WEMWBS10_post',
                 'WEMWBS11_post',
                 'WEMWBS12_post',
                 'WEMWBS13_post',
                 'WEMWBS14_post'
            ]])

# Checking for duplicate columns

In [14]:
def getDuplicateColumns(df):
  
    # Create an empty set
    duplicateColumnNames = set()
      
    # Iterate through all the columns 
    # of dataframe
    for x in range(df.shape[1]):
          
        # Take column at xth index.
        col = df.iloc[:, x]
          
        # Iterate through all the columns in
        # DataFrame from (x + 1)th index to
        # last index
        for y in range(x + 1, df.shape[1]):
              
            # Take column at yth index.
            otherCol = df.iloc[:, y]
              
            # Check if two columns at x & y
            # index are equal or not,
            # if equal then adding 
            # to the set
            if col.equals(otherCol):
                duplicateColumnNames.add(df.columns.values[y])
                  
    # Return list of unique column names 
    # whose contents are duplicates.
    return list(duplicateColumnNames)

In [15]:
getDuplicateColumns(c2_new)

['Trazadone:What is your currently prescribed anti-depressant? Please tick',
 'substance abuse disorder meds',
 'alcohol dependence meds']

In [16]:
# This line of code drops all of the duplicated columns, and keep the first one with a given name
# Only run if you're happy with removing them

c1_new = c1_new.loc[:,~c1_new.columns.duplicated(keep='first')]
c2_new = c2_new.loc[:,~c2_new.columns.duplicated(keep='first')]

## Merging data after column selection

In [17]:
c1c2_new = pd.concat([c1_new, c2_new], axis=0)
c1c2_new

,ID_baseline,Country_baseline,City_baseline,age,gender,nationality,education,Employment,LSD use,DMT use,Ayahuasca use,psychedelics use,Mescaline use,Salvia Divinorum use,Iboga use,Hallucinogen use,Other use,None psychedelics use,other1 use,number of times you have taken psychedelic,Amphetamines use,MDMA/Ecstasy use,Cocaine use,Opiates use,Benzodiazepines use,Ketamine use,None drugs use,Major depressive disorder,Bipolar disorder,Schizophrenia,Anxiety disorder,Substance abuse disorder,Alcohol dependence,Hallucinogen persisting perception disorder,Psychotic disorder,Personality disorder,ADHD,Obsessive compulsive disorder,Eating disorder,No disorder,treated with medications,Current use,Anti-depressants,Mood stabilisers,Anti-psychotics,ADHD medication,substance abuse disorder meds,alcohol dependence meds,No current meds,compound to take,...,Asian,American Indian or Alaskan Native,Native Hawaiian or Other Pacific Islander,Unknown,Not say,"Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, antipsychotics, ADHD medication, mood stabilisers)?",Fluoxetine:What is your currently prescribed anti-depressant? Please tick,Citalopram:What is your currently prescribed anti-depressant? Please tick,Sertraline:What is your currently prescribed anti-depressant? Please tick,Paroxetine:What is your currently prescribed anti-depressant? Please tick,Escitalopram:What is your currently prescribed anti-depressant? Please tick,Venlafaxine:What is your currently prescribed anti-depressant? Please tick,Duloxetine:What is your currently prescribed anti-depressant? Please tick,Trazadone:What is your currently prescribed anti-depressant? Please tick,Mirtazapine:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick.1,how long,plan to continue antidepressants,spiritual healing,Treatment of mental health problems,Healing physical illness,Spiritual experience:Can you indicate what your motives are to undergo a psychedelic ceremony?,Communication with the spirit world,How did you administer the drug?,Other - Write In:How did you administer the drug?,"Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†",How intense would you rate your psychedelic drug experience?,opiods,ASC47_Average,ASC48_Average,ASC49_Average,ASC50_Average,ASC51_Average,ASC52_Average,ASC53_Average,ASC54_Average,EDI9_Average,EDI10_Average,EDI11_Average,EDI12_Average,EDI13_Average,EDI14_Average,EDI15_Average,EDI16_Average,EDI17_Average,Body aches,Sweats or chills,Crying,Feeling hot or cold
URL Variable: sguid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0BywrMoxyK4CqTMrfzhRpBuPGt96G3J4,532.0,Canada,Toronto,23.0,Male,GB - United Kingdom,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-5 times,NaN,MDMA/Ecstasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0Ck8CVM19UcALyJD3GJeBIGFZfhobzUG,433.0,Canada,NaN,37.0,Male,CA - Canada,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,Salvia Divinorum,NaN,NaN,NaN,NaN,NaN,21-50 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,Benzodiazepines,Ketamine,NaN,NaN,NaN,NaN,Anxiety disorder,Substance abuse disorder,NaN,NaN,NaN,Personality disorder,NaN,NaN,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0d2Ei33sA5FI6lPfSvj2Cd6WI74Mz8Kn,69.0,Canada,Qu√©bec,35.0,Male,CA - Canada,Post-graduate degree (e.g. masters or doctorate),Full-time job,NaN,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only once,NaN,NaN,Cocaine,Opiates,Benzodiazepines,NaN,NaN,Major depressive disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Anti-depressants,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0GDq2cqvb1Oc9JXfbVHLsgMmKKrriJnb,219.0,United States,Ashburn,37.0,Male,US - United States,Post-graduate degree (e.g. masters or doctorate),Full-time job,LSD,DMT,Ayahuasca,Psilocybin / magic mushrooms / truffles,"Mescaline (Peyote, San Pedro)",NaN,NaN,"Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, ...",NaN,NaN,NaN,More than 100 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0HhrbLWHE8U4H89IuzKMG57pDS6ThiMD,231.0,Germany,Frankfurt,23.0,Male,IT - Italy,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times,Amphetamines,MDMA/Ecstasy,Cocaine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FnafwU24WNsajpTZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IaIlEW6dlKxpu6SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J8FRqdya59eAx6Cv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RrmjsV89nn5nri5Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tq7JzFnHzZtTRTj2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Recoding cohort 1 & 2 acute experience questionnaires to numeric values

### MEQ

In [18]:
MEQ = list(c1c2_new[c1c2_new.columns[pd.Series(c1c2_new.columns).str.startswith('MEQ')]])

question_list = MEQ

for question in question_list:
    c1c2_new[question] = c1c2_new[question].str[:1].astype(float)
    
for item in MEQ:
    c1c2_new['MEQ_Total'] = c1c2_new[[item]].mean(axis=1)*20

c1c2_new['MEQ_Total'].unique()

array([ nan, 100.,  80.,  60.,  40.,   0.,  20.])

### CEQ

In [19]:
c1c2_new['CEQ1_Average'].unique()

array([nan, 'None; not at all', 'Slight', 'So slight cannot decide',
       'Strong', 'Extreme (more than ever before in my life)', 'Moderate'],
      dtype=object)

In [20]:
CEQ = list(c1c2_new[c1c2_new.columns[pd.Series(c1c2_new.columns).str.startswith('CEQ')]])

ceq_word = ['None; not at all', 
                     'So slight cannot decide', 
                     'Slight', 
                     'Moderate',
                     'Strong', 
                     'Extreme (more than ever before in my life)']

scoring = [0, 1, 2, 3, 4, 5]

In [21]:
question_list = CEQ

for question in question_list:
    c1c2_new[question] = c1c2_new[question].replace(ceq_word, scoring)

In [22]:
for item in CEQ:
    c1c2_new['CEQ_Total'] = c1c2_new[[item]].mean(axis=1)*20

In [23]:
c1c2_new['CEQ_Total'].unique()

array([ nan,   0.,  40.,  20.,  60.,  80., 100.])

### EBI

In [24]:
EBI = list(c1c2_new[c1c2_new.columns[pd.Series(c1c2_new.columns).str.startswith('EBI')]])
EBI

['EBI1_Average',
 'EBI2_Average',
 'EBI3_Average',
 'EBI4_Average',
 'EBI5_Average',
 'EBI6_Average',
 'EBI7_Average',
 'EBI8_Average']

In [25]:
EBI_Averages = ['EBI1_Average','EBI2_Average','EBI3_Average','EBI5_Average','EBI6_Average','EBI8_Average']

In [26]:
for item in EBI_Averages:
    c1c2_new['EBI_Total'] = c1c2_new[[item]].mean(axis=1)
    
c1c2_new['EBI_Total'].unique()

array([ nan, 100.,  70.,  25.,  69.,  83.,  49.,  40.,  67.,  48.,  95.,
        55.,   0.,  90.,   7.,   8.,  74.,  12.,  30.,  96.,  44.,  64.,
        85.,   9.,  11.,   2.,  22.,  60.,  80.,  88.,   6.,  46.,  71.,
        68.,  81.,  79.,  66.,  35.,  50.,  56.,  98.,   5.,   4.,  72.,
        27.,  16.,  29.,  52.,  75.,  42.,  99.,  15.,  36.,  58.,  77.,
        13.,  82.,  62.,  34.,  87.,  32.,  10.,  38.,  93.,  92.,  18.,
        17.,  26.,  43.,  78.,  57.,  73.,  97.,  91.,  54.,  14.,  37.,
        20.,  53.,   1.,  61.,  86.,  76.,  21.,  84.,  94.,  45.,  59.,
        24.,  63.,  31.,  39.,  47.,   3.,  65.,  89.,  19.,  28.])

### EDI

In [27]:
EDI = list(c1c2_new[c1c2_new.columns[pd.Series(c1c2_new.columns).str.startswith('EDI')]])

for item in EDI:
    c1c2_new['EDI_Total'] = c1c2_new[[item]].mean(axis=1)
    
c1c2_new['EDI_Total'].unique()

array([ nan,  13.,   0.,  72.,   6.,  29.,  12.,  81.,  20.,  10.,  15.,
        26.,   4., 100.,  92.,  44.,   7.,  68.,  74.,  24.,   5.,   1.,
         9.,  91.,  14.,  70.,  11.,  62.,  30.,  67.,  40.,  50.,  99.,
        21.,  52.,  49.,  95.,  35.,   8.,  51.,  69.,  80.,  77.,  18.,
        28.,  89.,   2.,  19.,  55.,  75.,  23.,  56.,  65.,   3.,  42.,
        79.,  33.,  25.,  37.,  76.,  64.,  16.,  47.,  48.,  90.,  17.,
        82.,  61.,  71.,  87.,  98.,  86.,  94.,  78.,  59.,  85.,  22.,
        60.,  32.,  39.,  88.,  54.,  36.,  31.,  45.,  83.,  43.,  38.,
        66.,  46.])

### ASC

In [28]:
## We need to decide what type of scoring you want to use. Just some ASC questions? those included in c2?

ASC = list(c1c2_new[c1c2_new.columns[pd.Series(c1c2_new.columns).str.startswith('ASC')]])

for item in ASC:
    c1c2_new['ASC_Total'] = c1c2_new[[item]].sum(axis=1, skipna=False)
    
c1c2_new['ASC_Total'].unique()

array([ nan,   0.,   8.,   7.,   3.,  29.,  30.,  68., 100.,  70.,  34.,
        33.,  17.,   9.,  10.,  83.,  55.,  45.,  11.,   1.,  62.,  69.,
        78.,  75.,  40.,  18.,   6.,  23.,   4.,  50.,  16.,  19.,  12.,
        90.,  85.,  63.,   5.,  76.,  79.,  80.,  88.,  20.,  71.,  74.,
        49.,  24.,  95.,  64.,   2.,  89.,  98.,  15.,  93.,  52.,  96.,
        42.,  35.,  31.,  72.,  44.,  84.,  13.,  53.,  60.,  21.,  46.,
        41.,  25.,  73.,  59.,  43.,  67.,  38.,  56.,  22.,  99.,  14.,
        48.,  87.,  27.,  86.,  82.,  57.,  81.,  92.,  77.,  97.,  39.,
        61.,  94.,  32.,  51.,  58.,  28.,  54.])

In [29]:
c1c2_new

,ID_baseline,Country_baseline,City_baseline,age,gender,nationality,education,Employment,LSD use,DMT use,Ayahuasca use,psychedelics use,Mescaline use,Salvia Divinorum use,Iboga use,Hallucinogen use,Other use,None psychedelics use,other1 use,number of times you have taken psychedelic,Amphetamines use,MDMA/Ecstasy use,Cocaine use,Opiates use,Benzodiazepines use,Ketamine use,None drugs use,Major depressive disorder,Bipolar disorder,Schizophrenia,Anxiety disorder,Substance abuse disorder,Alcohol dependence,Hallucinogen persisting perception disorder,Psychotic disorder,Personality disorder,ADHD,Obsessive compulsive disorder,Eating disorder,No disorder,treated with medications,Current use,Anti-depressants,Mood stabilisers,Anti-psychotics,ADHD medication,substance abuse disorder meds,alcohol dependence meds,No current meds,compound to take,...,"Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, antipsychotics, ADHD medication, mood stabilisers)?",Fluoxetine:What is your currently prescribed anti-depressant? Please tick,Citalopram:What is your currently prescribed anti-depressant? Please tick,Sertraline:What is your currently prescribed anti-depressant? Please tick,Paroxetine:What is your currently prescribed anti-depressant? Please tick,Escitalopram:What is your currently prescribed anti-depressant? Please tick,Venlafaxine:What is your currently prescribed anti-depressant? Please tick,Duloxetine:What is your currently prescribed anti-depressant? Please tick,Trazadone:What is your currently prescribed anti-depressant? Please tick,Mirtazapine:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick.1,how long,plan to continue antidepressants,spiritual healing,Treatment of mental health problems,Healing physical illness,Spiritual experience:Can you indicate what your motives are to undergo a psychedelic ceremony?,Communication with the spirit world,How did you administer the drug?,Other - Write In:How did you administer the drug?,"Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†",How intense would you rate your psychedelic drug experience?,opiods,ASC47_Average,ASC48_Average,ASC49_Average,ASC50_Average,ASC51_Average,ASC52_Average,ASC53_Average,ASC54_Average,EDI9_Average,EDI10_Average,EDI11_Average,EDI12_Average,EDI13_Average,EDI14_Average,EDI15_Average,EDI16_Average,EDI17_Average,Body aches,Sweats or chills,Crying,Feeling hot or cold,MEQ_Total,CEQ_Total,EBI_Total,EDI_Total,ASC_Total
URL Variable: sguid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0BywrMoxyK4CqTMrfzhRpBuPGt96G3J4,532.0,Canada,Toronto,23.0,Male,GB - United Kingdom,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-5 times,NaN,MDMA/Ecstasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0Ck8CVM19UcALyJD3GJeBIGFZfhobzUG,433.0,Canada,NaN,37.0,Male,CA - Canada,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,Salvia Divinorum,NaN,NaN,NaN,NaN,NaN,21-50 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,Benzodiazepines,Ketamine,NaN,NaN,NaN,NaN,Anxiety disorder,Substance abuse disorder,NaN,NaN,NaN,Personality disorder,NaN,NaN,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,100.0,NaN,NaN
0d2Ei33sA5FI6lPfSvj2Cd6WI74Mz8Kn,69.0,Canada,Qu√©bec,35.0,Male,CA - Canada,Post-graduate degree (e.g. masters or doctorate),Full-time job,NaN,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only once,NaN,NaN,Cocaine,Opiates,Benzodiazepines,NaN,NaN,Major depressive disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Anti-depressants,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,40.0,70.0,NaN,NaN
0GDq2cqvb1Oc9JXfbVHLsgMmKKrriJnb,219.0,United States,Ashburn,37.0,Male,US - United States,Post-graduate degree (e.g. masters or doctorate),Full-time job,LSD,DMT,Ayahuasca,Psilocybin / magic mushrooms / truffles,"Mescaline (Peyote, San Pedro)",NaN,NaN,"Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, ...",NaN,NaN,NaN,More than 100 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0HhrbLWHE8U4H89IuzKMG57pDS6ThiMD,231.0,Germany,Frankfurt,23.0,Male,IT - Italy,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times,Amphetamines,MDMA/Ecstasy,Cocaine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,0.0,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FnafwU24WNsajpTZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IaIlEW6dlKxpu6SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J8FRqdya59eAx6Cv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RrmjsV89nn5nri5Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tq7JzFnHzZtTRTj2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Exporting cohort 1 & 2 data into one excel file

In [30]:
# ONLY REMOVE THE HASHTAG IF YOU WANT TO EXPORT IN THIS RUN

# c1c2_new.to_excel("c1c2_new_merged.xlsx")

# Ceremony questionnaire
#### We will first deal with the ceremony questionnaire names, because we need to calculate an average score for each participant from 5 acute timepoints.

In [31]:
# Now let's look at the ceremony data. 
# Because we have 5 acute timepoints we want to take a mean out of, 
# we need to rename columns into simple names with consistent spelling
# to make it easy to specify which ones we want to take a mean out of: 

# Renaming ceremony baseline data 

ceremony_baseline = (ceremony_baseline.rename(columns={
            "URL Variable: sguid": 'URL_baseline',
            "Response ID": 'ID_baseline',
            "Country": 'Country_baseline',
            "Your age:": 'age',
            "Your gender:": 'gender',
            "Nationality (e.g. GB = British; US = USA):": 'nationality',
            "Highest educational level attained:": 'education',
            "Employment:": 'Employment',
            "White:Ethnic group (check one or more):¬†": 'White',
            "Black or African American:Ethnic group (check one or more):¬†": 'Black or African American',
            "Asian:Ethnic group (check one or more):¬†": 'Asian',
            "American Indian or Alaskan Native:Ethnic group (check one or more):¬†": 'American Indian or Alaskan Native',
            "Native Hawaiian or Other Pacific Islander:Ethnic group (check one or more):¬†": 'Native Hawaiian or Other Pacific Islander',
            "Unknown:Ethnic group (check one or more):¬†": 'Unknown',
            "Prefer not to say:Ethnic group (check one or more):¬†": 'Not say',
            
            "LSD:Please indicate what psychedelics you have used in the past.": 'LSD use',
            "DMT:Please indicate what psychedelics you have used in the past.": 'DMT use',
            "Ayahuasca:Please indicate what psychedelics you have used in the past.": 'Ayahuasca use',
            "Psilocybin / magic mushrooms / truffles:Please indicate what psychedelics you have used in the past.": 'psychedelics use',
            "Mescaline (Peyote, San Pedro):Please indicate what psychedelics you have used in the past.": 'Mescaline use',
            "Salvia Divinorum:Please indicate what psychedelics you have used in the past.": 'Salvia Divinorum use',
            "Iboga / Ibogaine:Please indicate what psychedelics you have used in the past.": 'Iboga use',
            "Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, 2C-B, 4-ACO-DMT, 1P-LSD):Please indicate what psychedelics you have used in the past.": 'Hallucinogen use',
            "Other - Write In:Please indicate what psychedelics you have used in the past.": 'Other use',
            "None of the above:Please indicate what psychedelics you have used in the past.": 'None psychedelic use',
            "Other - Write In:Please indicate what psychedelics you have used in the past..1": 'other1 use',
            "Please indicate the number of times you have taken classic psychedelic substances (LSD, psilocybin, DMT, ayahuasca, mescaline).": 'number of times you have taken psychedelic',
            "Amphetamines:Please indicate what other drugs you have used at least once.": 'Amphetamines use',
            "MDMA/Ecstasy:Please indicate what other drugs you have used at least once.": 'MDMA/Ecstasy use',
            "Cocaine:Please indicate what other drugs you have used at least once.": 'Cocaine use',
            "Opiates:Please indicate what other drugs you have used at least once.": 'Opiates use',
            "Benzodiazepines:Please indicate what other drugs you have used at least once.": 'Benzodiazepines use',
            "Ketamine:Please indicate what other drugs you have used at least once.": 'Ketamine use',
            "None of the above:Please indicate what other drugs you have used at least once.": 'None drug use',
            "How regularly have you used any of these drugs described above over the past 6 months?": 'how regularly used',
    
            "Major depressive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Major depressive disorder',
            "Bipolar disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Bipolar disorder',
            "Schizophrenia:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Schizophrenia',
            "Anxiety disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Anxiety disorder',
            "Substance use disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Substance abuse disorder',
            "Alcohol dependence:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Alcohol dependence',
            "Hallucinogen persisting perception disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Hallucinogen persisting perception disorder',
            "Psychotic disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Psychotic disorder',
            "Personality disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Personality disorder',
            "ADHD:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'ADHD',
            "Obsessive compulsive disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Obsessive compulsive disorder',
            "Eating disorder:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'Eating disorder',
            "None of the above:Have you ever been diagnosed with one of the following psychiatric illnesses by a doctor or psychologist? Tick the box(es) that apply.": 'No disorder',
            "Are you planning to participate in a psychedelic ceremony with the intention to treat this / one of these psychiatric illnesses?": 'intention to treat',
            
            "Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, anti-psychotics, ADHD medication)?": 'treated with medications',
            "Are you currently using this/these medication(s)?": 'Current use',
            "Anti-depressants:What is your current prescribed medication?": 'Anti-depressants',
            "Mood stabilisers:What is your current prescribed medication?": 'Mood stabilisers',
            "Anti-psychotics:What is your current prescribed medication?": 'Anti-psychotics',
            "ADHD medication:What is your current prescribed medication?": 'ADHD medication',
            'Medication for substance abuse disorder:What is your current prescribed medication?': 'substance abuse disorder meds',
            "Medication for alcohol dependence:What is your current prescribed medication?": 'alcohol dependence meds',
            "None of the above:What is your current prescribed medication?": 'No current meds',
            "What is your currently prescribed anti-depressant?": 'name of antidepressant',
            "Other - Write In:What is your currently prescribed anti-depressant?": 'other antidepressants',
            "For how long have you been using prescribed anti-depressants?": 'how long',
            "Are you planning to stop or pause taking the prescribed medication for your planned psychedelic ceremony experience?": 'plan to continue antidepressants',
            
            "What type of psychedelic / plant medicine do you anticipate to use in your upcoming experience?": 'compound to take',
            "Other - Write In:What type of psychedelic / plant medicine do you anticipate to use in your upcoming experience?": 'other compound',
            "Psilocybin / magic mushrooms/ truffles:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking psychedelics',
            "LSD / 1P-LSD:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking LSD',
            "Ayahuasca:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking Ayahuasca',
            "DMT / 5-MeO-DMT:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking DMT',
            "Salvia divinorum:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking Salvia divinorum',
            "San Pedro:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking San Pedro',
            "Peyote:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking Peyote',
            "Iboga / ibogaine:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking Iboga',
            "Other - Write In:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required)": 'plan taking Other',
            "Other - Write In:Which are the psychedelics / plant medicines that you anticipate to use? (minimum 2 required).1": 'plan taking Other1',

             'Fun / recreational / party:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Fun / recreational / party',
             'Spiritual healing:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'spiritual healing',
             'Treatment of mental health problems:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Treatment of mental health problems',
             'Healing of physical illness:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Healing physical illness',
             'Spiritual experience:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Spiritual',
             'Religious practice:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Religious practice',
             'Curiosity:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Curiosity',
             'Social:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Social',
             'Connection with nature:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Connection with nature',
             'Communication with the spirit world:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'Communication with the spirit world',
             'To escape from difficult emotions:Can you indicate what your motives are to undergo a ceremony / guided psychedelic experience?': 'escape from difficult emotions',
           
            "I've been feeling optimistic about the future.": 'WEMWBS1_baseline',
            "I've been feeling useful.": 'WEMWBS2_baseline',
            "I've been feeling relaxed.": 'WEMWBS3_baseline',
            "I've been feeling interested in other people.¬†": 'WEMWBS4_baseline',
            "I've had energy to spare.": 'WEMWBS5_baseline',
            "I've been dealing with problems well.¬†": 'WEMWBS6_baseline',
            "I've been thinking clearly.": 'WEMWBS7_baseline',
            "I've been feeling good about myself.¬†": 'WEMWBS8_baseline',
            "I've been feeling close to other people.¬†": 'WEMWBS9_baseline',
            "I've been feeling confident.": 'WEMWBS10_baseline',
            "I've been able to make up my own mind about things.¬†": 'WEMWBS11_baseline',
            "I've been feeling loved.¬†": 'WEMWBS12_baseline',
            "I am interested in new things.¬†": 'WEMWBS13_baseline',
            "I've been feeling cheerful.¬†": 'WEMWBS14_baseline',
         }))

In [32]:
# As this action will be repeated for multiple dataframes, you don't want to type them up every time.
# First step is to define a list of dataframes that you want to apply the column name changes to. 

datasets = [ceremony_acute_1, ceremony_acute_2, ceremony_acute_3, ceremony_acute_4, ceremony_acute_5]

for dataset in datasets:
    dataset = dataset.rename(columns={
            # Acute 
            "Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to the typical dose that was given during the ceremony.¬† If you asked for or received a smaller or higher dose than what was handed out, please indicate the appropriate answer below. If you do not know what dose you have received, you could consider asking the facilitator or shaman. ¬†": 'total dose',
            "Cannabis:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Cannabis',
            "Alcohol:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Alcohol',
            "Kambo:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Kambo',
            "Tobacco:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Tobacco',
            "Sananga:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Sananga',
            "Coca :Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Coca',
            "Rap√©:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Rap√©',
            '"heart opener" (mdma or MDA):Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?': 'MDMA/ecstasy',
            "Ayahuasca :Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Ayahuasca',
            "DMT:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'DMT',
            "Ecstasy:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'MDMA/ecstasy',
            "LSD:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'LSD',
            "MDMA:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'MDMA/ecstasy',
            "Magic Truffles:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Magic Truffles',
            "Mushrooms:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin',
            "Mushrooms :Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin',
            "Psilocybin:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin Truffles',
            "Psilocybin :Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin',
            "Psilocybin Truffles:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Magic Psilocybin',
            "Psilosybin:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin',
            "Psylociben:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Psilocybin',
            "Psylocibin:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Magic Truffles',
            "Psylocybin:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Magic Truffles',
            "The two plants of ayahuasca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'two plants of ayahuasca',
            "Truffles:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Truffles',
            "Truffles :Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Truffles',
            "ayahuasca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'Ayahuasca',
            "nicotine vape:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'nicotine vape',
            "none:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?": 'none',

            #SE Ceremony 
            "Nausea or vomiting:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'nausea',
            "Diarrhea:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Diarrhea',
            "Body aches:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Body aches',
            "Ringing in the ears:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Ringing in the ears',
            "Headache:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Headache',
            "Sweats or chills:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Sweats or chills',
            "Trembling:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Trembling',
            "Crying:Have you experienced any of the following bodily effects during the session / ceremony:¬†": 'Crying',
          
            ## MEQ 
             "Freedom from the limitations of your personal self and feeling a unity or bond with what was felt to be greater than your personal self.": 'MEQ1',
             'Experience of pure being and pure awareness (beyond the world of sense impressions).': 'MEQ2',
             'Experience of oneness in relation to an "inner world" within.': 'MEQ3',
             'Experience of the fusion of your personal self into a larger whole.': 'MEQ4',
             'Experience of unity with ultimate reality.': 'MEQ5',
             'Feeling that you experienced eternity or infinity.': 'MEQ6',
             """Experience of oneness or unity with objects and/or persons perceived in your surroundings.""": 'MEQ7',
             """Experience of the insight that "all is One".""": 'MEQ8',
             'Awareness of the life or living presence in all things.': 'MEQ9',
             'Gain of insightful knowledge experienced at an intuitive level.': 'MEQ10',
             'Certainty of encounter with ultimately reality (in sense of being able to "know" and "see" what is really real at some point during your experience).': 'MEQ11',
             'You are convinced now, as you look back on your experience, that in it you encountered ultimate reality (i.e. that you "knew" and "saw" what was really real).': 'MEQ12',
             'Sense of being at a spiritual height.': 'MEQ13',
             'Sense of Reverence.': 'MEQ14',
             'Feeling that you experienced something profoundly sacred and holy.': 'MEQ15',
             'Experience of amazement.': 'MEQ16',
             'Feelings of tenderness and gentleness.': 'MEQ17',
             'Feelings of peace and tranquillity.': 'MEQ18',
             'Experience of ecstasy.': 'MEQ19',
             'Sense of awe or awesomeness.': 'MEQ20',
             'Feelings of joy.': 'MEQ21',
             'Loss of your usual sense of time.': 'MEQ22',
             'Loss of your usual sense of space.': 'MEQ23',
             'Loss of usual awareness of where you were.': 'MEQ24',
             'Sense of being "outside of" time, beyond past and future.': 'MEQ25',
             'Being in a realm with no space boundaries.': 'MEQ26',
             'Experience of timelessness.': 'MEQ27',
             'Sense that the experience cannot be described adequately in words.': 'MEQ28',
             'Feeling that you could not do justice to your experience by describing it in words.': 'MEQ29',
             'Feeling that it would be difficult to communicate your own experience to others who have not had similar experiences.': 'MEQ30',
            
            ## EDI
             'I felt especially assertive¬†': 'EDI1',
             'I experienced a dissolution of my "self" or ego.': 'EDI2',
             'I felt more important or special than others': 'EDI3',
             'I felt at one with the universe.': 'EDI4',
             'My ego felt inflated': 'EDI5',
             'I felt a sense of union with others.': 'EDI6',
             'I felt especially sure-of-myself¬†': 'EDI7',
             'I experienced a decrease in my sense of self-importance.': 'EDI8',
             'I felt especially keen and competitive': 'EDI9',
             'I experienced a disintegration of my "self" or ego.': 'EDI10',
             "I felt like my viewpoint was worth more than other peoples'": 'EDI11',
             'I felt far less absorbed by my own issues and concerns.': 'EDI12',
             'I felt especially self-confident': 'EDI13',
             'I lost all sense of ego.': 'EDI14',
             'I felt especially self-assured': 'EDI15',
             'All notion of self and identity dissolved away.': 'EDI16',
            
            ## EBI
             'I faced emotionally difficult feelings that I usually push aside.': 'EBI1',
             """I experienced a resolution of a personal conflict/trauma""": 'EBI2',
             'I felt able to explore challenging emotions and memories.': 'EBI3',
             'I was resisting and avoiding challenging feelings throughout, without breakthrough.': 'EBI4',
             'I had an emotional breakthrough.¬†': 'EBI5',
             'I was able to get a sense of closure on an emotional problem.': 'EBI6',
             'I felt emotionally stuck throughout, without breakthrough.': 'EBI7',
             'I achieved an emotional release followed by a sense of relief.': 'EBI8',
            ## CEQ            
             'Isolation and loneliness': 'CEQ1',
             'Sadness': 'CEQ2',
             'Feeling my heart beating': 'CEQ3',
             'I had the feeling something horrible would happen': 'CEQ4',
             """Feeling my body shake/tremble""": 'CEQ5',
             'Feelings of grief': 'CEQ6',
             'Experience of fear': 'CEQ7',
             'Fear that I might lose my mind or go insane': 'CEQ8',
             'I felt like crying': 'CEQ9',
             'Feeling of isolation from people and things': 'CEQ10',
             'Feelings of despair': 'CEQ11',
             'I had the feeling that people were plotting against me': 'CEQ12',
             'I was afraid that the state I was in would last forever': 'CEQ13',
             'Anxiousness': 'CEQ14',
             'I felt shaky inside': 'CEQ15',
             'I had the profound experience of my own death': 'CEQ16',
             'I felt my heart beating irregularly or skipping beats¬†': 'CEQ17',
             'Pressure or weight in my chest or abdomen': 'CEQ18',
             'I experienced a decreased sense of sanity¬†': 'CEQ19',
             'I felt as if I was dead or dying': 'CEQ20',
             'Panic': 'CEQ21',
             'Experience of antagonism toward people around me': 'CEQ22',
             'Despair': 'CEQ23',
             'I felt isolated from everything and everyone': 'CEQ24',
             """Emotional and/or physical suffering""": 'CEQ25',
             'I felt frightened': 'CEQ26',
            ## ASC
             'I saw regular patterns in complete darkness or with closed eyes.': 'ASC1',
             'I saw colours in complete darkness or with closed eyes.': 'ASC2',
             'I saw brightness or flashes in complete darkness or with closed eyes.': 'ASC3',
             'I saw whole scenes roll by with closed eyes or in complete darkness.': 'ASC4',
             'I could see images from my memory or imagination with extreme clarity.': 'ASC5',
             'My imagination was extremely vivid.': 'ASC6',
             'Sounds seemed to influence what I saw.': 'ASC7',
             'Shapes seemed to be changed by sounds or noises.': 'ASC8',
             'The colors of things seemed to be altered by sounds or noises.': 'ASC9'
    
    
    }, inplace=True)

In [33]:
#renaming ceremony post data 
ceremony_post = (ceremony_post.rename(columns={
            
       #4 weeks
            "URL Variable: sguid": 'URL_post',
            "Response ID": 'ID_post',
            "I've been feeling optimistic about the future.": 'WEMWBS1_post',
            "I've been feeling useful.": 'WEMWBS2_post',
            "I've been feeling relaxed.": 'WEMWBS3_post',
            "I've been feeling interested in other people.¬†": 'WEMWBS4_post',
            "I've had energy to spare.": 'WEMWBS5_post',
            "I've been dealing with problems well.¬†": 'WEMWBS6_post',
            "I've been thinking clearly.": 'WEMWBS7_post',
            "I've been feeling good about myself.¬†": 'WEMWBS8_post',
            "I've been feeling close to other people.¬†": 'WEMWBS9_post',
            "I've been feeling confident.": 'WEMWBS10_post',
            "I've been able to make up my own mind about things.¬†": 'WEMWBS11_post',
            "I've been feeling loved.¬†": 'WEMWBS12_post',
            "I am interested in new things.¬†": 'WEMWBS13_post',
            "I've been feeling cheerful.¬†": 'WEMWBS14_post'
                 }))

In [34]:
# As we will want to take a mean of each of the acute timepoints, 
# we need to label them to distinguish between them. You can do that
# By adding a 'suffix' i.e. a symbol at the end of every column. 
# Here we will add numbers at the end of each column to mark which 
# timepoint does it belong to. 

ceremony_acute_1 = ceremony_acute_1.add_suffix('_1')
ceremony_acute_2 = ceremony_acute_2.add_suffix('_2')
ceremony_acute_3 = ceremony_acute_3.add_suffix('_3')
ceremony_acute_4 = ceremony_acute_4.add_suffix('_4')
ceremony_acute_5 = ceremony_acute_5.add_suffix('_5')

In [35]:
# Here we will merge all of the different ceremony timepoints into one data frame. 

ceremony = pd.concat([ceremony_baseline, ceremony_acute_1, ceremony_acute_2, ceremony_acute_3, ceremony_acute_4, ceremony_acute_5, ceremony_post], axis=1)

## MEQ

In [36]:
# In order to be able to take out means from each of the columns
# we need to make sure that the answers are coded properly.
# In Python this means that the object type will be called 'float64',
# simply meaning a numeric format with a decimal place (e.g. 5.0). 

# First step is to check the current wording of input in each of the columns. 
# If the wording contains actual words/text, it automatically means that 
# Python will treat this input as an 'object', and mathematical operations will not be available

# We can use the 'unique' function to list all of the unique inputs in a given column.

ceremony['MEQ1_1'].unique()

array(['5= Extreme (more than any other time in my life and stronger than 4)',
       nan, '0= None; not at all',
       '4= Strong (equivalent in degree to any other strong experience)',
       '3= Moderate', '2= Slight', '1= So slight cannot decide'],
      dtype=object)

In [37]:
# You can see that for MEQ we have 6 different input options,
# and there is an easy way to convert it to numerical format.

# The most straightforward way will be to just keep the first character (e.g. 0, 5, etc.)
# And convert the format of the column to numeric (float64). 

# Let's give it a go... 

# First, we want to create a list which will contain all of the columns 
# which belong to the MEQ questionnaire. 

# You can type it in manually, like this: 
# MEQ = [MEQ1_1, MEQ1_2 ... ]
# but this takes a lot of time and it's easy to make an error. 

# Every time something takes a lot of time and it feels like you can make an error,
# you can probably find a smarter way to do it. 

# A smart way would be to create a list through a "filter", 
# so all columns which start with the name MEQ will be added to it. 

# "str.startswith('text')" will let us do it in 1 line. 

MEQ = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ')]])
MEQ

['MEQ1_1',
 'MEQ2_1',
 'MEQ3_1',
 'MEQ4_1',
 'MEQ5_1',
 'MEQ6_1',
 'MEQ7_1',
 'MEQ8_1',
 'MEQ9_1',
 'MEQ10_1',
 'MEQ11_1',
 'MEQ12_1',
 'MEQ13_1',
 'MEQ14_1',
 'MEQ15_1',
 'MEQ16_1',
 'MEQ17_1',
 'MEQ18_1',
 'MEQ19_1',
 'MEQ20_1',
 'MEQ21_1',
 'MEQ22_1',
 'MEQ23_1',
 'MEQ24_1',
 'MEQ25_1',
 'MEQ26_1',
 'MEQ27_1',
 'MEQ28_1',
 'MEQ29_1',
 'MEQ30_1',
 'MEQ1_2',
 'MEQ2_2',
 'MEQ3_2',
 'MEQ4_2',
 'MEQ5_2',
 'MEQ6_2',
 'MEQ7_2',
 'MEQ8_2',
 'MEQ9_2',
 'MEQ10_2',
 'MEQ11_2',
 'MEQ12_2',
 'MEQ13_2',
 'MEQ14_2',
 'MEQ15_2',
 'MEQ16_2',
 'MEQ17_2',
 'MEQ18_2',
 'MEQ19_2',
 'MEQ20_2',
 'MEQ21_2',
 'MEQ22_2',
 'MEQ23_2',
 'MEQ24_2',
 'MEQ25_2',
 'MEQ26_2',
 'MEQ27_2',
 'MEQ28_2',
 'MEQ29_2',
 'MEQ30_2',
 'MEQ1_3',
 'MEQ2_3',
 'MEQ3_3',
 'MEQ4_3',
 'MEQ5_3',
 'MEQ6_3',
 'MEQ7_3',
 'MEQ8_3',
 'MEQ9_3',
 'MEQ10_3',
 'MEQ11_3',
 'MEQ12_3',
 'MEQ13_3',
 'MEQ14_3',
 'MEQ15_3',
 'MEQ16_3',
 'MEQ17_3',
 'MEQ18_3',
 'MEQ19_3',
 'MEQ20_3',
 'MEQ21_3',
 'MEQ22_3',
 'MEQ23_3',
 'MEQ24_3',
 'MEQ25_3',
 'MEQ26_3',
 'MEQ27_3',
 'MEQ28_3',
 'MEQ29_3',
 'MEQ30_3',
 'MEQ1_4',
 'MEQ2_4',
 'MEQ3_4',
 'MEQ4_4',
 'MEQ5_4',
 'MEQ6_4',
 'MEQ7_4',
 'MEQ8_4',
 'MEQ9_4',
 'MEQ10_4',
 'MEQ11_4',
 'MEQ12_4',
 'MEQ13_4',
 'MEQ14_4',
 'MEQ15_4',
 'MEQ16_4',
 'MEQ17_4',
 'MEQ18_4',
 'MEQ19_4',
 'MEQ20_4',
 'MEQ21_4',
 'MEQ22_4',
 'MEQ23_4',
 'MEQ24_4',
 'MEQ25_4',
 'MEQ26_4',
 'MEQ27_4',
 'MEQ28_4',
 'MEQ29_4',
 'MEQ30_4',
 'MEQ1_5',
 'MEQ2_5',
 'MEQ3_5',
 'MEQ4_5',
 'MEQ5_5',
 'MEQ6_5',
 'MEQ7_5',
 'MEQ8_5',
 'MEQ9_5',
 'MEQ10_5',
 'MEQ11_5',
 'MEQ12_5',
 'MEQ13_5',
 'MEQ14_5',
 'MEQ15_5',
 'MEQ16_5',
 'MEQ17_5',
 'MEQ18_5',
 'MEQ19_5',
 'MEQ20_5',
 'MEQ21_5',
 'MEQ22_5',
 'MEQ23_5',
 'MEQ24_5',
 'MEQ25_5',
 'MEQ26_5',
 'MEQ27_5',
 'MEQ28_5',
 'MEQ29_5',
 'MEQ30_5']

In [38]:
# Once we have our list ready, we can try to run this other clever function. 
# First, we need to define which questions are we going to use for this run: 

question_list = MEQ

# And now for every item of the MEQ list, i.e. for every question, we want to:  

    # 1) only keep the first character (which will be a number) 
    # This is done using '.str[:1]' 
    # where 1 stands for the number of characters you want to keep
    
    # 2) and convert the format to numeric ('float64')
    # This is done by adding the following expression: 
    # '.astype(float)'

for question in question_list:
    ceremony[question] = ceremony[question].str[:1].astype(float)
    
# Let's check if it worked in a random column:

ceremony['MEQ5_1'].unique()

array([ 5., nan,  0.,  3.,  2.,  4.,  1.])

In [39]:
# Fantastic :) Hopefully this worked! 

# Now the next and final step for MEQ is to create a new column 
# which will contain the mean scores for every question across different timepoints.

# First, we will create a list for every question across different timepoints, for example: 

MEQ1 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ1_')]]

# After we view it, we can see that it contains timepoints 1-5 for MEQ1.  

MEQ1.columns.tolist()

['MEQ1_1', 'MEQ1_2', 'MEQ1_3', 'MEQ1_4', 'MEQ1_5']

In [40]:
# Now we'll do the same thing for all of the other questions.
# For sure there's another way to do it so it's not so text heavy, 
# but for now this will do. I will think of something else later. 

MEQ2 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ2_')]]
MEQ3 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ3_')]]
MEQ4 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ4_')]]
MEQ5 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ5_')]]
MEQ6 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ6_')]]
MEQ7 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ7_')]]
MEQ8 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ8_')]]
MEQ9 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ9_')]]
MEQ10 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ10_')]]
MEQ11 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ11_')]]
MEQ12 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ12_')]]
MEQ13 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ13_')]]
MEQ14 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ14_')]]
MEQ15 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ15_')]]
MEQ16 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ16_')]]
MEQ17 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ17_')]]
MEQ18 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ18_')]]
MEQ19 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ19_')]]
MEQ20 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ20_')]]
MEQ21 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ21_')]]
MEQ22 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ22_')]]
MEQ23 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ23_')]]
MEQ24 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ24_')]]
MEQ25 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ25_')]]
MEQ26 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ26_')]]
MEQ27 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ27_')]]
MEQ28 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ28_')]]
MEQ29 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ29_')]]
MEQ30 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ30_')]]


# Let's check a random question and see if it worked: 

MEQ19.columns.tolist()

['MEQ19_1', 'MEQ19_2', 'MEQ19_3', 'MEQ19_4', 'MEQ19_5']

In [41]:
# Okay, looks like it worked (hopefully!)
# Now the next step is to create a new column 
# which will contain the mean out of all different timepoints 
# and then multiply by 2

# How to score MEQ 
# 0 – none; not at all; 
# 1 – so slight cannot decide; 
# 2 – slight; 
# 3 – moderate; 
# 4 – strong (equivalent in degree to any other strong experience); 
# 5 – extreme (more than any other time in my life and stronger than 4) ;
# —> Average 30 items and multiply with 20

ceremony['MEQ1_Average'] = MEQ1.mean(axis=1)
ceremony['MEQ2_Average'] = MEQ2.mean(axis=1)
ceremony['MEQ3_Average'] = MEQ3.mean(axis=1)
ceremony['MEQ4_Average'] = MEQ4.mean(axis=1)
ceremony['MEQ5_Average'] = MEQ5.mean(axis=1)
ceremony['MEQ6_Average'] = MEQ6.mean(axis=1)
ceremony['MEQ7_Average'] = MEQ7.mean(axis=1)
ceremony['MEQ8_Average'] = MEQ8.mean(axis=1)
ceremony['MEQ9_Average'] = MEQ9.mean(axis=1)
ceremony['MEQ10_Average'] = MEQ10.mean(axis=1)
ceremony['MEQ11_Average'] = MEQ11.mean(axis=1)
ceremony['MEQ12_Average'] = MEQ12.mean(axis=1)
ceremony['MEQ13_Average'] = MEQ13.mean(axis=1)
ceremony['MEQ14_Average'] = MEQ14.mean(axis=1)
ceremony['MEQ15_Average'] = MEQ15.mean(axis=1)
ceremony['MEQ16_Average'] = MEQ16.mean(axis=1)
ceremony['MEQ17_Average'] = MEQ17.mean(axis=1)
ceremony['MEQ18_Average'] = MEQ18.mean(axis=1)
ceremony['MEQ19_Average'] = MEQ19.mean(axis=1)
ceremony['MEQ20_Average'] = MEQ20.mean(axis=1)
ceremony['MEQ21_Average'] = MEQ21.mean(axis=1)
ceremony['MEQ22_Average'] = MEQ22.mean(axis=1)
ceremony['MEQ23_Average'] = MEQ23.mean(axis=1)
ceremony['MEQ24_Average'] = MEQ24.mean(axis=1)
ceremony['MEQ25_Average'] = MEQ25.mean(axis=1)
ceremony['MEQ26_Average'] = MEQ26.mean(axis=1)
ceremony['MEQ27_Average'] = MEQ27.mean(axis=1)
ceremony['MEQ28_Average'] = MEQ28.mean(axis=1)
ceremony['MEQ29_Average'] = MEQ29.mean(axis=1)
ceremony['MEQ30_Average'] = MEQ30.mean(axis=1)

# Let's check a random column and see if it worked: 

ceremony['MEQ18_Average'].unique()

array([3.8       ,        nan, 0.        , 3.        , 4.        ,
       3.25      , 3.33333333, 2.66666667, 5.        , 2.        ,
       2.33333333, 2.5       , 1.        , 3.5       , 1.33333333,
       4.5       , 3.66666667, 4.75      , 0.5       , 4.33333333,
       4.66666667, 1.5       , 1.66666667, 1.6       ])

In [42]:
MEQ_updated = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('MEQ')]])
m = re.compile("^MEQ.*Average$")
MEQ_Averages = list(filter(m.match, MEQ_updated))
print(MEQ_Averages)

['MEQ1_Average', 'MEQ2_Average', 'MEQ3_Average', 'MEQ4_Average', 'MEQ5_Average', 'MEQ6_Average', 'MEQ7_Average', 'MEQ8_Average', 'MEQ9_Average', 'MEQ10_Average', 'MEQ11_Average', 'MEQ12_Average', 'MEQ13_Average', 'MEQ14_Average', 'MEQ15_Average', 'MEQ16_Average', 'MEQ17_Average', 'MEQ18_Average', 'MEQ19_Average', 'MEQ20_Average', 'MEQ21_Average', 'MEQ22_Average', 'MEQ23_Average', 'MEQ24_Average', 'MEQ25_Average', 'MEQ26_Average', 'MEQ27_Average', 'MEQ28_Average', 'MEQ29_Average', 'MEQ30_Average']

In [43]:
for item in MEQ_Averages:
    ceremony['MEQ_Total'] = ceremony[[item]].mean(axis=1)*20

In [44]:
ceremony['MEQ_Total'].unique()

array([ 88.        ,          nan,  60.        , 100.        ,
        20.        ,  75.        ,  93.33333333,  80.        ,
        40.        ,  53.33333333,  50.        ,  66.66666667,
        73.33333333,   0.        ,  46.66666667,  86.66666667,
         5.        ,  26.66666667,  33.33333333,  70.        ,
        90.        ,  30.        ,  35.        ,  10.        ,
        28.        ])

## CEQ

In [45]:
ceremony['CEQ1_1'].unique()

array(['None; not at all', nan, 'Slight', 'Strong', 'Moderate',
       'So slight cannot decide',
       'Extreme (more than ever before in my life)'], dtype=object)

In [46]:
CEQ = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ')]])
CEQ

['CEQ1_1',
 'CEQ2_1',
 'CEQ3_1',
 'CEQ4_1',
 'CEQ5_1',
 'CEQ6_1',
 'CEQ7_1',
 'CEQ8_1',
 'CEQ9_1',
 'CEQ10_1',
 'CEQ11_1',
 'CEQ12_1',
 'CEQ13_1',
 'CEQ14_1',
 'CEQ15_1',
 'CEQ16_1',
 'CEQ17_1',
 'CEQ18_1',
 'CEQ19_1',
 'CEQ20_1',
 'CEQ21_1',
 'CEQ22_1',
 'CEQ23_1',
 'CEQ24_1',
 'CEQ25_1',
 'CEQ26_1',
 'CEQ1_2',
 'CEQ2_2',
 'CEQ3_2',
 'CEQ4_2',
 'CEQ5_2',
 'CEQ6_2',
 'CEQ7_2',
 'CEQ8_2',
 'CEQ9_2',
 'CEQ10_2',
 'CEQ11_2',
 'CEQ12_2',
 'CEQ13_2',
 'CEQ14_2',
 'CEQ15_2',
 'CEQ16_2',
 'CEQ17_2',
 'CEQ18_2',
 'CEQ19_2',
 'CEQ20_2',
 'CEQ21_2',
 'CEQ22_2',
 'CEQ23_2',
 'CEQ24_2',
 'CEQ25_2',
 'CEQ26_2',
 'CEQ1_3',
 'CEQ2_3',
 'CEQ3_3',
 'CEQ4_3',
 'CEQ5_3',
 'CEQ6_3',
 'CEQ7_3',
 'CEQ8_3',
 'CEQ9_3',
 'CEQ10_3',
 'CEQ11_3',
 'CEQ12_3',
 'CEQ13_3',
 'CEQ14_3',
 'CEQ15_3',
 'CEQ16_3',
 'CEQ17_3',
 'CEQ18_3',
 'CEQ19_3',
 'CEQ20_3',
 'CEQ21_3',
 'CEQ22_3',
 'CEQ23_3',
 'CEQ24_3',
 'CEQ25_3',
 'CEQ26_3',
 'CEQ1_4',
 'CEQ2_4',
 'CEQ3_4',
 'CEQ4_4',
 'CEQ5_4',
 'CEQ6_4',
 'CEQ7_4',
 'CEQ8_4',
 'CEQ9_4',
 'CEQ10_4',
 'CEQ11_4',
 'CEQ12_4',
 'CEQ13_4',
 'CEQ14_4',
 'CEQ15_4',
 'CEQ16_4',
 'CEQ17_4',
 'CEQ18_4',
 'CEQ19_4',
 'CEQ20_4',
 'CEQ21_4',
 'CEQ22_4',
 'CEQ23_4',
 'CEQ24_4',
 'CEQ25_4',
 'CEQ26_4',
 'CEQ1_5',
 'CEQ2_5',
 'CEQ3_5',
 'CEQ4_5',
 'CEQ5_5',
 'CEQ6_5',
 'CEQ7_5',
 'CEQ8_5',
 'CEQ9_5',
 'CEQ10_5',
 'CEQ11_5',
 'CEQ12_5',
 'CEQ13_5',
 'CEQ14_5',
 'CEQ15_5',
 'CEQ16_5',
 'CEQ17_5',
 'CEQ18_5',
 'CEQ19_5',
 'CEQ20_5',
 'CEQ21_5',
 'CEQ22_5',
 'CEQ23_5',
 'CEQ24_5',
 'CEQ25_5',
 'CEQ26_5']

In [47]:
ceremony_ceq_word = ['None; not at all', 
                     'So slight cannot decide', 
                     'Slight', 
                     'Moderate',
                     'Strong', 
                     'Extreme (more than ever before in my life)']

scoring = [0, 1, 2, 3, 4, 5]
    
ceremony['CEQ1_1'] = ceremony['CEQ1_1'].replace(ceremony_ceq_word, scoring)

ceremony['CEQ1_1'].unique()

array([ 0., nan,  2.,  4.,  3.,  1.,  5.])

In [48]:
ceremony['CEQ1_1'].dtype

dtype('float64')

In [49]:
CEQ = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ')]])
CEQ

['CEQ1_1',
 'CEQ2_1',
 'CEQ3_1',
 'CEQ4_1',
 'CEQ5_1',
 'CEQ6_1',
 'CEQ7_1',
 'CEQ8_1',
 'CEQ9_1',
 'CEQ10_1',
 'CEQ11_1',
 'CEQ12_1',
 'CEQ13_1',
 'CEQ14_1',
 'CEQ15_1',
 'CEQ16_1',
 'CEQ17_1',
 'CEQ18_1',
 'CEQ19_1',
 'CEQ20_1',
 'CEQ21_1',
 'CEQ22_1',
 'CEQ23_1',
 'CEQ24_1',
 'CEQ25_1',
 'CEQ26_1',
 'CEQ1_2',
 'CEQ2_2',
 'CEQ3_2',
 'CEQ4_2',
 'CEQ5_2',
 'CEQ6_2',
 'CEQ7_2',
 'CEQ8_2',
 'CEQ9_2',
 'CEQ10_2',
 'CEQ11_2',
 'CEQ12_2',
 'CEQ13_2',
 'CEQ14_2',
 'CEQ15_2',
 'CEQ16_2',
 'CEQ17_2',
 'CEQ18_2',
 'CEQ19_2',
 'CEQ20_2',
 'CEQ21_2',
 'CEQ22_2',
 'CEQ23_2',
 'CEQ24_2',
 'CEQ25_2',
 'CEQ26_2',
 'CEQ1_3',
 'CEQ2_3',
 'CEQ3_3',
 'CEQ4_3',
 'CEQ5_3',
 'CEQ6_3',
 'CEQ7_3',
 'CEQ8_3',
 'CEQ9_3',
 'CEQ10_3',
 'CEQ11_3',
 'CEQ12_3',
 'CEQ13_3',
 'CEQ14_3',
 'CEQ15_3',
 'CEQ16_3',
 'CEQ17_3',
 'CEQ18_3',
 'CEQ19_3',
 'CEQ20_3',
 'CEQ21_3',
 'CEQ22_3',
 'CEQ23_3',
 'CEQ24_3',
 'CEQ25_3',
 'CEQ26_3',
 'CEQ1_4',
 'CEQ2_4',
 'CEQ3_4',
 'CEQ4_4',
 'CEQ5_4',
 'CEQ6_4',
 'CEQ7_4',
 'CEQ8_4',
 'CEQ9_4',
 'CEQ10_4',
 'CEQ11_4',
 'CEQ12_4',
 'CEQ13_4',
 'CEQ14_4',
 'CEQ15_4',
 'CEQ16_4',
 'CEQ17_4',
 'CEQ18_4',
 'CEQ19_4',
 'CEQ20_4',
 'CEQ21_4',
 'CEQ22_4',
 'CEQ23_4',
 'CEQ24_4',
 'CEQ25_4',
 'CEQ26_4',
 'CEQ1_5',
 'CEQ2_5',
 'CEQ3_5',
 'CEQ4_5',
 'CEQ5_5',
 'CEQ6_5',
 'CEQ7_5',
 'CEQ8_5',
 'CEQ9_5',
 'CEQ10_5',
 'CEQ11_5',
 'CEQ12_5',
 'CEQ13_5',
 'CEQ14_5',
 'CEQ15_5',
 'CEQ16_5',
 'CEQ17_5',
 'CEQ18_5',
 'CEQ19_5',
 'CEQ20_5',
 'CEQ21_5',
 'CEQ22_5',
 'CEQ23_5',
 'CEQ24_5',
 'CEQ25_5',
 'CEQ26_5']

In [50]:
question_list = CEQ

for question in question_list:
    ceremony[question] = ceremony[question].replace(ceremony_ceq_word, scoring)

In [51]:
ceremony['CEQ10_1'].unique()

array([ 0., nan,  2.,  1.,  3.,  5.,  4.])

In [52]:
CEQ1 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ1_')]]

# After we view it, we can see that it contains timepoints 1-5 for MEQ1.  

CEQ2 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ2_')]]
CEQ3 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ3_')]]
CEQ4 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ4_')]]
CEQ5 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ5_')]]
CEQ6 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ6_')]]
CEQ7 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ7_')]]
CEQ8 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ8_')]]
CEQ9 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ9_')]]
CEQ10 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ10_')]]
CEQ11 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ11_')]]
CEQ12 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ12_')]]
CEQ13 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ13_')]]
CEQ14 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ14_')]]
CEQ15 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ15_')]]
CEQ16 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ16_')]]
CEQ17 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ17_')]]
CEQ18 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ18_')]]
CEQ19 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ19_')]]
CEQ20 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ20_')]]
CEQ21 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ21_')]]
CEQ22 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ22_')]]
CEQ23 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ23_')]]
CEQ24 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ24_')]]
CEQ25 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ25_')]]
CEQ26 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ26_')]]

CEQ19.columns.tolist()

['CEQ19_1', 'CEQ19_2', 'CEQ19_3', 'CEQ19_4', 'CEQ19_5']

In [53]:
# Average of 5 timepoints for CEQ

ceremony['CEQ1_Average'] = CEQ1.mean(axis=1)
ceremony['CEQ2_Average'] = CEQ2.mean(axis=1)
ceremony['CEQ3_Average'] = CEQ3.mean(axis=1)
ceremony['CEQ4_Average'] = CEQ4.mean(axis=1)
ceremony['CEQ5_Average'] = CEQ5.mean(axis=1)
ceremony['CEQ6_Average'] = CEQ6.mean(axis=1)
ceremony['CEQ7_Average'] = CEQ7.mean(axis=1)
ceremony['CEQ8_Average'] = CEQ8.mean(axis=1)
ceremony['CEQ9_Average'] = CEQ9.mean(axis=1)
ceremony['CEQ10_Average'] = CEQ10.mean(axis=1)
ceremony['CEQ11_Average'] = CEQ11.mean(axis=1)
ceremony['CEQ12_Average'] = CEQ12.mean(axis=1)
ceremony['CEQ13_Average'] = CEQ13.mean(axis=1)
ceremony['CEQ14_Average'] = CEQ14.mean(axis=1)
ceremony['CEQ15_Average'] = CEQ15.mean(axis=1)
ceremony['CEQ16_Average'] = CEQ16.mean(axis=1)
ceremony['CEQ17_Average'] = CEQ17.mean(axis=1)
ceremony['CEQ18_Average'] = CEQ18.mean(axis=1)
ceremony['CEQ19_Average'] = CEQ19.mean(axis=1)
ceremony['CEQ20_Average'] = CEQ20.mean(axis=1)
ceremony['CEQ21_Average'] = CEQ21.mean(axis=1)
ceremony['CEQ22_Average'] = CEQ22.mean(axis=1)
ceremony['CEQ23_Average'] = CEQ23.mean(axis=1)
ceremony['CEQ24_Average'] = CEQ24.mean(axis=1)
ceremony['CEQ25_Average'] = CEQ25.mean(axis=1)
ceremony['CEQ26_Average'] = CEQ26.mean(axis=1)

ceremony['CEQ1_Average'].unique()

array([1.6       ,        nan, 2.        , 0.        , 4.        ,
       2.5       , 1.        , 0.66666667, 1.66666667, 0.5       ,
       2.66666667, 3.        , 5.        , 1.33333333, 2.25      ,
       3.5       , 2.33333333, 1.5       , 4.66666667, 3.33333333,
       0.33333333, 4.5       , 4.33333333, 3.66666667])

In [54]:
# Scoring CEQ: average the quesitons and multiply by 20

# How to score CEQ 
# 0 - none; not at all
# 1 - so slight cannot decide
# 2 - slight
# 3 - moderate
# 4 – strong
# 5 – extreme (more than ever before in my life) 
# —> Average 26 items and multiply with 20

CEQ_updated = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('CEQ')]])
r = re.compile("^CEQ.*Average$")
CEQ_Averages = list(filter(r.match, CEQ_updated)) # Read Note below
print(CEQ_Averages)

['CEQ1_Average', 'CEQ2_Average', 'CEQ3_Average', 'CEQ4_Average', 'CEQ5_Average', 'CEQ6_Average', 'CEQ7_Average', 'CEQ8_Average', 'CEQ9_Average', 'CEQ10_Average', 'CEQ11_Average', 'CEQ12_Average', 'CEQ13_Average', 'CEQ14_Average', 'CEQ15_Average', 'CEQ16_Average', 'CEQ17_Average', 'CEQ18_Average', 'CEQ19_Average', 'CEQ20_Average', 'CEQ21_Average', 'CEQ22_Average', 'CEQ23_Average', 'CEQ24_Average', 'CEQ25_Average', 'CEQ26_Average']

In [55]:
for item in CEQ_Averages:
    ceremony['CEQ_Total'] = ceremony[[item]].mean(axis=1)*20

In [56]:
ceremony['CEQ_Total'].unique()

array([  8.        ,          nan,  80.        ,   0.        ,
        20.        ,  10.        ,  60.        ,  30.        ,
         6.66666667,  40.        ,  26.66666667,  90.        ,
        66.66666667,  33.33333333,  86.66666667,  53.33333333,
        50.        , 100.        ,  13.33333333,  46.66666667,
        70.        ,  28.        ])

## EBI

In [57]:
ceremony['EBI1_1'].unique()

array([ 50.,  nan,   3.,  87.,  94.,   0.,  30.,  95.,  97., 100.,  70.,
        52.,  67.,  63.,  65.,  80.,  74.,  60.,  18.,   5.,  68.,  98.,
        83.,   6.,  14.,  13.,   2.,  91.,  12.,   1.,  85.,  25.,  79.,
        82.,  19.,  35.,  75.,  86.,  96.,  15.,  10.,  22.,  37.,  47.,
        73.,  71.,  51.,  88.,  93.,  53.,  76.,  90.,  61.,  24.,  20.,
        69.,  55.,  16.,  59.,  72.,  26.,   9.,  11.,  64.,   8.,  77.,
        40.,  62.,  45.,  36.,  66.,  81.,  31.,  99.,  92.,  84.,  49.,
        58.,  21.,  32.,  54.,   7.,  17.,   4.,  89.,  57.,  78.,  39.,
        29.,  34.])

In [58]:
EBI = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI')]])
EBI

['EBI1_1',
 'EBI2_1',
 'EBI3_1',
 'EBI4_1',
 'EBI5_1',
 'EBI6_1',
 'EBI7_1',
 'EBI8_1',
 'EBI1_2',
 'EBI2_2',
 'EBI3_2',
 'EBI4_2',
 'EBI5_2',
 'EBI6_2',
 'EBI7_2',
 'EBI8_2',
 'EBI1_3',
 'EBI2_3',
 'EBI3_3',
 'EBI4_3',
 'EBI5_3',
 'EBI6_3',
 'EBI7_3',
 'EBI8_3',
 'EBI1_4',
 'EBI2_4',
 'EBI3_4',
 'EBI4_4',
 'EBI5_4',
 'EBI6_4',
 'EBI7_4',
 'EBI8_4',
 'EBI1_5',
 'EBI2_5',
 'EBI3_5',
 'EBI4_5',
 'EBI5_5',
 'EBI6_5',
 'EBI7_5',
 'EBI8_5']

In [59]:
EBI1 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI1_')]]

# After we view it, we can see that it contains timepoints 1-5 for EBI1.  

EBI2 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI2_')]]
EBI3 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI3_')]]
EBI4 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI4_')]]
EBI5 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI5_')]]
EBI6 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI6_')]]
EBI7 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI7_')]]
EBI8 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EBI8_')]]

EBI5.columns.tolist()

['EBI5_1', 'EBI5_2', 'EBI5_3', 'EBI5_4', 'EBI5_5']

In [60]:
# EBI mean scores across different timepoints

ceremony['EBI1_Average'] = EBI1.mean(axis=1)
ceremony['EBI2_Average'] = EBI2.mean(axis=1)
ceremony['EBI3_Average'] = EBI3.mean(axis=1)
ceremony['EBI4_Average'] = EBI4.mean(axis=1)
ceremony['EBI5_Average'] = EBI5.mean(axis=1)
ceremony['EBI6_Average'] = EBI6.mean(axis=1)
ceremony['EBI7_Average'] = EBI7.mean(axis=1)
ceremony['EBI8_Average'] = EBI8.mean(axis=1)

# Let's check a random column and see if it worked: 

ceremony['EBI5_Average'].unique()

array([ 56.2       ,          nan,   6.        ,  84.        ,
        90.        ,   0.        ,  68.75      ,  62.        ,
        97.        , 100.        ,  46.        ,  78.66666667,
        51.        ,  77.        ,  81.        ,  11.66666667,
        47.        ,  30.5       ,  98.        ,  27.        ,
        18.5       ,  99.        ,   4.        ,  44.33333333,
        96.        ,  95.        ,  48.        ,  59.        ,
        60.        ,  38.        ,  67.        ,  20.33333333,
        57.        ,  39.        ,  56.33333333,  65.        ,
        12.5       ,   5.        ,   0.66666667,  53.33333333,
        32.33333333,   0.25      ,  20.        ,  56.66666667,
        97.5       ,  33.5       ,  62.66666667,  30.66666667,
        88.66666667,  29.33333333,  36.        ,  55.        ,
         2.        ,  64.        ,  61.        ,  69.        ,
        25.        ,  45.        ,  40.        ,  79.        ,
        21.        ,  66.        ,  28.33333333,  43.        ,
        27.33333333,  57.5       ,  63.66666667,  24.        ,
        63.        ,  96.5       ,  86.        ,  31.        ,
        41.        ,  87.        ,  71.5       ,  78.        ,
        91.        ,  89.        ,  16.        ,  88.33333333,
        27.5       ,  70.        ,   8.        ,  88.        ,
        88.5       ,  71.        ,  50.        ,  73.        ,
        56.        ,  96.66666667,   3.        ,  11.        ,
        64.5       ,  94.        ,  59.5       ,  76.        ,
        49.        ,  92.        ,  75.        ,  93.        ,
        10.        ,  35.        ,  72.5       ,  85.        ,
        37.5       ,  70.5       ,  17.        ,  38.66666667,
        83.        ,  82.        ,  15.        ,  42.5       ,
        33.        ,  32.        ,  45.66666667,  43.33333333,
         7.        ,  51.33333333,  78.33333333,  99.33333333,
        25.5       ,  12.        ,  80.        ,  72.        ,
        36.5       ,  68.        ,  51.66666667,  47.33333333,
        30.        ,   1.        ,  53.        ,  22.        ,
        26.        ,  14.        ,  65.5       ,  22.25      ,
        80.5       ,  23.        ,   2.5       ,  74.        ,
        34.33333333,  36.66666667,  52.5       ,  58.        ,
        66.66666667,  28.66666667,  19.5       ,  65.66666667,
        22.5       ,  24.33333333,  39.33333333,  91.5       ,
        31.66666667,  15.66666667,   2.33333333,  44.        ,
        54.        ,  13.        ,  52.        ,  18.        ,
        37.        ,  32.5       ,   0.33333333,  26.5       ])

In [61]:
# How to score EBI
# 4 and 7 reversed score 
# —> average of 6 items 

# Questions 1-3, 5-6, and 8 normal scoring

In [62]:
EBI_Averages = ['EBI1_Average','EBI2_Average','EBI3_Average','EBI5_Average','EBI6_Average','EBI8_Average']
EBI_Averages

['EBI1_Average',
 'EBI2_Average',
 'EBI3_Average',
 'EBI5_Average',
 'EBI6_Average',
 'EBI8_Average']

In [63]:
for item in EBI_Averages:
    ceremony['EBI_Total'] = ceremony[[item]].mean(axis=1)
    
ceremony['EBI_Total'].unique()

array([ 49.4       ,          nan,   0.        ,  77.        ,
        56.        ,  42.5       ,  45.        ,  16.66666667,
        24.66666667,  85.        ,  93.        ,  45.5       ,
        66.33333333,  52.        ,  73.5       ,  71.        ,
        28.33333333, 100.        ,  70.        ,  38.5       ,
        98.        ,  25.66666667,  54.5       ,  91.        ,
        32.66666667,  97.        ,  54.        ,  29.        ,
        60.        ,  17.        ,  74.        ,  69.        ,
        78.        ,  47.66666667,  75.        ,  13.5       ,
         5.        ,  10.33333333,  66.        ,  33.33333333,
         1.25      ,  50.5       ,  80.        ,  50.        ,
        10.        ,  61.66666667,   1.5       ,  32.        ,
        65.33333333,  63.66666667,  25.33333333,  80.33333333,
        39.        ,  46.33333333,  25.        ,   2.        ,
        23.        ,  78.33333333,  28.        ,  97.33333333,
        52.66666667,  15.        ,  43.        ,  16.33333333,
        67.        ,  64.5       ,  55.33333333,  42.        ,
        89.        ,  96.        ,  47.5       ,  86.        ,
        88.        ,  74.5       ,  49.        ,  61.        ,
        59.        ,  65.        ,  90.        ,   6.        ,
        92.        ,  91.66666667,  36.        ,  95.        ,
        30.5       ,   8.        ,  17.75      ,  53.        ,
        98.5       ,  58.        ,  99.        ,  71.5       ,
        88.66666667,   1.        ,  47.        ,  16.        ,
        76.        ,  82.        ,  73.        ,  81.        ,
        79.        ,  84.        ,  94.        ,  40.        ,
        37.        ,   9.        ,  20.        ,  57.        ,
        21.        ,   3.        ,  31.66666667,  62.        ,
        17.5       ,  50.66666667,  51.66666667,  19.33333333,
        52.33333333,   8.5       ,  63.        ,  55.        ,
        13.        ,   7.        ,  33.        ,  14.        ,
        44.66666667,  21.66666667,  64.        ,  48.        ,
        26.        ,  95.33333333,  41.        ,  87.        ,
        31.        ,  18.        ,  11.        ,  68.        ,
        51.        ,  72.        ,  84.5       ,  24.        ,
        75.5       ,  23.5       ,  12.66666667,   4.5       ,
        30.33333333,  58.33333333,   1.33333333,  56.33333333,
        93.5       ,  23.33333333,   6.5       ,  66.66666667,
        46.        ,  81.5       ,  38.        ,  31.33333333,
        64.33333333,  53.33333333,  37.6       ,  12.        ,
        48.5       ,  31.5       ,  27.        ,   0.66666667,
        67.75      ])

## EDI

In [64]:
ceremony['EDI1_1'].unique()

array([  0.,  nan,  71.,  41.,   2.,   7.,  14.,  35.,  10.,   1.,  92.,
        50.,   6.,  42.,  55.,  18.,  70.,  12.,   4., 100.,  81.,   8.,
        93.,  73.,  69.,   5.,  17.,  85.,   3.,  51.,  20.,  48.,  90.,
        75.,  56.,  23.,  30.,  46.,  13.,  16.,  94.,  77.,  25.,  88.,
        26.,  62.,  65.,  22.,  37.,  11.,  89.,  95.,  59.,  31.,  96.,
        78.,  28.,  19.,  60.,  79.,  86.,  74.,  64.,  53.,  87.,  80.,
        24.,  99.,   9.,  29.,  40.,  61.,  76.,  33.,  47.,  54.,  15.,
        49.,  66.,  68.,  32.,  44.,  52.,  67.,  21.,  91.,  57.,  82.,
        43.,  72.])

In [65]:
EDI = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI')]])
EDI

['EDI1_1',
 'EDI2_1',
 'EDI3_1',
 'EDI4_1',
 'EDI5_1',
 'EDI6_1',
 'EDI7_1',
 'EDI8_1',
 'EDI9_1',
 'EDI10_1',
 'EDI11_1',
 'EDI12_1',
 'EDI13_1',
 'EDI14_1',
 'EDI15_1',
 'EDI16_1',
 'EDI1_2',
 'EDI2_2',
 'EDI3_2',
 'EDI4_2',
 'EDI5_2',
 'EDI6_2',
 'EDI7_2',
 'EDI8_2',
 'EDI9_2',
 'EDI10_2',
 'EDI11_2',
 'EDI12_2',
 'EDI13_2',
 'EDI14_2',
 'EDI15_2',
 'EDI16_2',
 'EDI1_3',
 'EDI2_3',
 'EDI3_3',
 'EDI4_3',
 'EDI5_3',
 'EDI6_3',
 'EDI7_3',
 'EDI8_3',
 'EDI9_3',
 'EDI10_3',
 'EDI11_3',
 'EDI12_3',
 'EDI13_3',
 'EDI14_3',
 'EDI15_3',
 'EDI16_3',
 'EDI1_4',
 'EDI2_4',
 'EDI3_4',
 'EDI4_4',
 'EDI5_4',
 'EDI6_4',
 'EDI7_4',
 'EDI8_4',
 'EDI9_4',
 'EDI10_4',
 'EDI11_4',
 'EDI12_4',
 'EDI13_4',
 'EDI14_4',
 'EDI15_4',
 'EDI16_4',
 'EDI1_5',
 'EDI2_5',
 'EDI3_5',
 'EDI4_5',
 'EDI5_5',
 'EDI6_5',
 'EDI7_5',
 'EDI8_5',
 'EDI9_5',
 'EDI10_5',
 'EDI11_5',
 'EDI12_5',
 'EDI13_5',
 'EDI14_5',
 'EDI15_5',
 'EDI16_5']

In [66]:
EDI1 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI1_')]]

# After we view it, we can see that it contains timepoints 1-5 for MEQ1.  

EDI1.columns.tolist()

['EDI1_1', 'EDI1_2', 'EDI1_3', 'EDI1_4', 'EDI1_5']

In [67]:
EDI2 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI2_')]]
EDI3 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI3_')]]
EDI4 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI4_')]]
EDI5 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI5_')]]
EDI6 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI6_')]]
EDI7 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI7_')]]
EDI8 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI8_')]]
EDI9 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI9_')]]
EDI10 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI10_')]]
EDI11 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI11_')]]
EDI12 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI12_')]]
EDI13 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI13_')]]
EDI14 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI14_')]]
EDI15 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI15_')]]
EDI16 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI16_')]]

# Let's check a random question and see if it worked: 

EDI12.columns.tolist()

['EDI12_1', 'EDI12_2', 'EDI12_3', 'EDI12_4', 'EDI12_5']

In [68]:
ceremony['EDI1_Average'] = EDI1.mean(axis=1)
ceremony['EDI2_Average'] = EDI2.mean(axis=1)
ceremony['EDI3_Average'] = EDI3.mean(axis=1)
ceremony['EDI4_Average'] = EDI4.mean(axis=1)
ceremony['EDI5_Average'] = EDI5.mean(axis=1)
ceremony['EDI6_Average'] = EDI6.mean(axis=1)
ceremony['EDI7_Average'] = EDI7.mean(axis=1)
ceremony['EDI8_Average'] = EDI8.mean(axis=1)
ceremony['EDI9_Average'] = EDI9.mean(axis=1)
ceremony['EDI10_Average'] = EDI10.mean(axis=1)
ceremony['EDI11_Average'] = EDI11.mean(axis=1)
ceremony['EDI12_Average'] = EDI12.mean(axis=1)
ceremony['EDI13_Average'] = EDI13.mean(axis=1)
ceremony['EDI14_Average'] = EDI14.mean(axis=1)
ceremony['EDI15_Average'] = EDI15.mean(axis=1)
ceremony['EDI16_Average'] = EDI16.mean(axis=1)

# Let's check a random column and see if it worked: 

ceremony['EDI12_Average'].unique()

array([ 10.8       ,          nan,  31.        ,  20.        ,
        94.        ,   0.        ,  36.25      ,  70.        ,
        53.33333333,  50.        ,  90.        ,  52.5       ,
        65.        ,  59.        ,  49.        ,  71.        ,
        31.66666667, 100.        ,  48.        ,  10.5       ,
         1.33333333,   1.5       ,  88.        ,  30.        ,
        46.66666667,  60.        ,  73.        ,  92.        ,
        29.        ,   5.        ,  43.        ,  40.        ,
        34.        ,  19.        ,  43.33333333,   4.        ,
        69.        ,   8.5       ,  38.        ,  85.        ,
        73.66666667,  52.33333333,  15.25      ,  97.        ,
         7.        ,  45.        ,  33.33333333,  96.        ,
        37.5       ,  55.        ,  55.66666667,  24.        ,
         7.33333333,  35.66666667,  35.        ,  12.        ,
        66.        ,   2.        ,  28.33333333,  37.33333333,
        69.66666667,   2.66666667,  25.        ,  99.        ,
        56.33333333,  80.        ,  41.66666667,  44.        ,
        67.        ,  75.        ,  56.5       ,  95.        ,
         6.        ,  76.        ,  57.        ,  36.        ,
        54.        ,  58.        ,  10.        ,  89.        ,
        21.        ,  86.        ,  74.75      ,   3.        ,
        46.        ,   5.33333333,   1.        ,  78.        ,
        71.5       ,  47.        ,  61.        ,  52.        ,
        87.5       ,  41.5       ,  82.        ,  47.33333333,
        56.        ,  15.        ,  83.        ,  11.        ,
        91.        ,  48.33333333,  32.66666667,  39.        ,
        37.66666667,  13.        ,  79.        ,  37.        ,
         8.        ,  23.5       ,  64.        ,  36.5       ,
        16.        ,  59.5       ,  68.33333333,  84.        ,
        27.        ,  63.        ,  58.66666667,  18.        ,
        42.        ,  53.        ,  93.        ,  68.        ,
        78.5       ,  62.        ,   2.5       ,  26.        ,
        72.        ,  17.        ,   3.5       ,  43.66666667,
         7.5       ,  77.        ,  68.5       ,  74.33333333,
        11.33333333,  22.5       ,  63.33333333,  60.66666667,
        35.5       ,  74.        ,  66.66666667,  22.        ,
         9.66666667,  14.        ,  34.66666667,  81.        ,
        58.33333333,  76.33333333,  64.66666667,   4.5       ,
        51.33333333,  42.66666667,  15.2       ,  98.        ,
        61.5       ,  66.5       ,   9.        ,  48.5       ,
        49.75      ])

In [69]:
#How to score EDI 
#average of 8  items

In [70]:
EDI_updated = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('EDI')]])
r = re.compile("^EDI.*Average$")
EDI_Averages = list(filter(r.match, EDI_updated))

for item in EDI_Averages:
    ceremony['EDI_Total'] = ceremony[[item]].mean(axis=1)
    
ceremony['EDI_Total'].unique()

array([ 14.6       ,          nan,   5.        ,  37.        ,
       100.        ,   0.        ,  46.        ,  90.        ,
        14.        ,  31.5       ,  35.33333333,  48.        ,
        81.        ,  91.        ,  34.        ,   6.66666667,
        10.        ,  20.        ,  98.        ,  87.        ,
         1.        ,  17.66666667,   2.        ,  85.        ,
        80.        ,  44.        ,  36.        ,  74.        ,
        38.        ,  88.        ,  16.        ,  39.        ,
        97.        ,   3.5       ,  11.        ,  27.33333333,
         2.33333333,  15.        ,   7.        ,  45.        ,
        17.5       ,  93.5       ,  29.        ,  64.        ,
         2.66666667,  60.        ,  30.33333333,  13.        ,
        37.33333333,   2.5       ,  41.        ,   4.        ,
        75.        ,  13.33333333,  15.66666667,  62.33333333,
        51.        ,   8.        ,  12.        ,  47.5       ,
        42.        ,  19.        ,  71.        ,  53.        ,
        25.        ,  29.5       ,  50.        ,  58.        ,
        70.        ,  30.        ,  99.        ,  32.66666667,
        23.        ,  22.        ,  52.        ,   6.        ,
        76.        ,  24.75      ,  67.        ,  27.        ,
        40.        ,  49.        ,  24.5       ,  57.        ,
        43.        ,  78.        ,  24.        ,  61.        ,
         9.        ,  93.        ,  65.        ,  87.5       ,
        66.        ,  18.        ,  72.        ,  33.        ,
        35.        ,  31.        ,  92.        ,  14.66666667,
        51.66666667,  48.33333333,  84.        ,  56.        ,
         3.        ,  41.5       ,  23.5       ,  69.        ,
        25.5       ,  16.66666667,  49.33333333,  21.        ,
        17.        ,  63.        ,  68.33333333,  26.        ,
        79.        ,  86.        ,  32.        ,  82.        ,
        49.5       ,  13.5       ,  76.5       ,  21.5       ,
        25.33333333,  33.33333333,  96.        ,  56.66666667,
        36.66666667,  83.33333333,  16.5       ,  79.66666667,
        47.        ,  89.        ,  62.5       ,  95.        ,
        59.66666667,  35.5       ,   3.66666667,   5.2       ,
        43.5       ,  77.        ,  48.5       ,   1.33333333,
        37.5       ,  54.        ])

## ASC

In [71]:
ceremony['ASC1_1'].unique()

array([100.,  nan,  68.,   0.,  10.,  98.,  85.,  35.,  92.,   1.,  73.,
        84.,  12.,  77.,  96.,  89.,  15.,  14.,  88.,  80.,   7.,   3.,
        91.,  99.,  49.,  50.,  60.,  30.,   5.,  70.,  95.,  61.,  72.,
        20.,  86.,  65.,  47.,  81.,  75.,  74.,  25.,  18.,  90.,  28.,
        79.,  23.,  78.,  58.,  66.,   2.,  67.,  26.,  51.,  76.,  27.,
        21.,  93.,  63.,  87.,  57.,  64.,  94.,  33.,  46.,   8.,   4.,
        34.,  16.,  62.,  97.,  32.,  55.,  53.,  24.,  38.,  31.,  82.,
         6.,  45.,  83.,  43.,   9.,  71.,  41.,  19.,  48.,  11.,  69.,
        17.,  40.,  56.])

In [72]:
ASC = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC')]])

ASC1 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC1_')]]
ASC2 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC2_')]]
ASC3 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC3_')]]
ASC4 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC4_')]]
ASC5 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC5_')]]
ASC6 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC6_')]]
ASC7 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC7_')]]
ASC8 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC8_')]]
ASC9 = ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC9_')]]

ceremony['ASC1_Average'] = ASC1.mean(axis=1)
ceremony['ASC2_Average'] = ASC2.mean(axis=1)
ceremony['ASC3_Average'] = ASC3.mean(axis=1)
ceremony['ASC4_Average'] = ASC4.mean(axis=1)
ceremony['ASC5_Average'] = ASC5.mean(axis=1)
ceremony['ASC6_Average'] = ASC6.mean(axis=1)
ceremony['ASC7_Average'] = ASC7.mean(axis=1)
ceremony['ASC8_Average'] = ASC8.mean(axis=1)
ceremony['ASC9_Average'] = ASC9.mean(axis=1)
ceremony['ASC8_Average'].unique()

array([ 38.2       ,          nan,  46.        ,  65.        ,
        93.        ,  40.        ,  77.75      ,   0.        ,
        65.66666667,  70.        ,  90.        ,  37.5       ,
        46.33333333,  66.        ,  87.        ,  62.        ,
        86.66666667, 100.        ,  47.        ,  71.33333333,
         2.5       ,  89.        ,  16.        ,  51.33333333,
        96.        ,  85.        ,  88.        ,   5.        ,
        42.        ,  74.        ,  16.66666667,   1.        ,
        10.        ,   3.5       ,  30.33333333,  81.        ,
        87.33333333,   7.        ,  94.        ,  55.        ,
        13.5       ,  75.        ,  80.        ,   0.5       ,
        25.33333333,  55.66666667,  21.33333333,  56.        ,
         9.        ,  45.        ,  12.        ,  79.        ,
        84.        ,  54.        ,  23.33333333,  34.        ,
        33.33333333,  28.        ,  13.66666667,  25.        ,
        50.        ,  44.33333333,  72.        ,  12.5       ,
        87.5       ,   6.33333333,  99.        ,  76.        ,
        37.        ,   6.        ,  64.        ,  27.        ,
         4.        ,  39.        ,  24.        ,   8.        ,
        95.        ,  13.        ,  83.        ,  49.        ,
        43.33333333,  17.        ,  97.        ,   6.5       ,
        35.        ,  58.5       ,  29.        ,   8.5       ,
        21.        ,  78.        ,  38.33333333,  82.        ,
        98.        ,  77.        ,   2.        ,  20.        ,
        48.        ,  68.        ,  71.5       ,  62.5       ,
        73.        ,  18.        ,  14.        ,  15.        ,
        54.66666667,  51.66666667,  52.        ,   1.66666667,
         5.33333333,  35.5       ,  92.        ,  71.        ,
        89.5       ,  53.        ,  60.        ,  32.5       ,
        63.        ,   3.        ,  59.        ,  67.        ,
        91.        ,  61.        ,  80.5       ,  96.5       ,
        86.        ,  23.75      ,   9.5       ,  58.66666667,
        26.66666667,  58.        ,  60.5       ,  46.5       ,
        11.66666667,   8.33333333,  33.66666667,  23.66666667,
         0.33333333,  34.33333333,   9.33333333,  30.        ,
        38.5       ,  32.        ,  27.33333333,  88.5       ,
        84.5       ,  44.5       ,  10.66666667,  23.        ,
        79.33333333,   3.66666667,  57.        ,  79.66666667,
        53.5       ,  78.5       ,  24.5       ,  43.        ,
         1.33333333,  95.5       ,  41.        ])

In [73]:
# How to score ASC
# Sum of all answers 

ASC_updated = list(ceremony[ceremony.columns[pd.Series(ceremony.columns).str.startswith('ASC')]])
a = re.compile("^ASC.*Average$")
ASC_Averages = list(filter(a.match, ASC_updated))

for item in ASC_Averages:
    ceremony['ASC_Total'] = ceremony[[item]].sum(axis=1, )
    
ceremony['ASC_Total'].unique()

array([ 42.8       ,   0.        ,  83.        ,   8.        ,
        67.        ,  47.        ,  67.25      ,  89.33333333,
        70.        ,  89.        ,  40.5       ,  59.        ,
        86.5       ,  92.        ,  71.        ,  86.66666667,
       100.        ,  27.        ,  32.        ,  73.66666667,
         2.5       ,  90.        ,   2.        ,  98.        ,
        75.        ,  81.        ,  51.        ,  85.        ,
        38.        ,  94.        ,  26.        ,  15.        ,
         3.        ,  10.        ,   7.5       ,  29.33333333,
        77.        ,  87.33333333,  93.        ,  25.        ,
        20.5       ,  80.        ,   6.        ,  44.5       ,
        22.        ,  33.66666667,  17.33333333,  57.66666667,
        12.33333333,  45.        ,  50.        ,  68.        ,
        82.        ,  44.        ,  18.33333333,  64.        ,
        33.33333333,   1.        ,   9.66666667,   4.33333333,
        23.        ,  36.33333333,  17.        ,  11.        ,
        82.5       ,  99.        ,  20.        ,  73.        ,
        37.5       ,  54.        ,   5.        ,  51.5       ,
        86.        ,  28.        ,   4.        ,  16.        ,
        13.        ,  46.        ,  73.33333333,  18.        ,
        30.        ,  91.        ,  53.        ,  36.        ,
        60.        ,   1.5       ,  55.        ,  74.        ,
        38.66666667,  48.        ,  65.        ,  12.        ,
        84.        ,  63.        ,  65.5       ,  58.        ,
        32.33333333,  57.        ,  14.        ,  97.        ,
        22.33333333,  43.33333333,   6.33333333,  61.        ,
        66.66666667,  79.        ,  24.        ,  35.        ,
        76.        ,   7.        ,  92.5       ,  16.33333333,
        66.        ,  37.        ,   2.66666667,  31.        ,
         3.5       ,  87.        ,  72.        ,  39.        ,
        62.5       ,  69.        ,  32.5       ,   0.5       ,
        70.5       ,  95.        ,   9.        ,  61.33333333,
        23.33333333,  21.        ,  56.5       ,  43.5       ,
        11.66666667,  30.33333333,   0.33333333,  33.        ,
         8.33333333,  49.        ,  35.5       ,   1.66666667,
        28.33333333,  52.        ,  66.5       ,  40.        ,
         9.33333333,  31.66666667,  10.66666667,  81.66666667,
        19.        ,  43.        ,  17.5       ,  80.33333333,
         1.6       ,  49.5       ,  29.        ,   0.66666667,
        95.75      ,  78.        ])

In [74]:
c1c2_new

,ID_baseline,Country_baseline,City_baseline,age,gender,nationality,education,Employment,LSD use,DMT use,Ayahuasca use,psychedelics use,Mescaline use,Salvia Divinorum use,Iboga use,Hallucinogen use,Other use,None psychedelics use,other1 use,number of times you have taken psychedelic,Amphetamines use,MDMA/Ecstasy use,Cocaine use,Opiates use,Benzodiazepines use,Ketamine use,None drugs use,Major depressive disorder,Bipolar disorder,Schizophrenia,Anxiety disorder,Substance abuse disorder,Alcohol dependence,Hallucinogen persisting perception disorder,Psychotic disorder,Personality disorder,ADHD,Obsessive compulsive disorder,Eating disorder,No disorder,treated with medications,Current use,Anti-depressants,Mood stabilisers,Anti-psychotics,ADHD medication,substance abuse disorder meds,alcohol dependence meds,No current meds,compound to take,...,"Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, antipsychotics, ADHD medication, mood stabilisers)?",Fluoxetine:What is your currently prescribed anti-depressant? Please tick,Citalopram:What is your currently prescribed anti-depressant? Please tick,Sertraline:What is your currently prescribed anti-depressant? Please tick,Paroxetine:What is your currently prescribed anti-depressant? Please tick,Escitalopram:What is your currently prescribed anti-depressant? Please tick,Venlafaxine:What is your currently prescribed anti-depressant? Please tick,Duloxetine:What is your currently prescribed anti-depressant? Please tick,Trazadone:What is your currently prescribed anti-depressant? Please tick,Mirtazapine:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick,Other - Write In:What is your currently prescribed anti-depressant? Please tick.1,how long,plan to continue antidepressants,spiritual healing,Treatment of mental health problems,Healing physical illness,Spiritual experience:Can you indicate what your motives are to undergo a psychedelic ceremony?,Communication with the spirit world,How did you administer the drug?,Other - Write In:How did you administer the drug?,"Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†",How intense would you rate your psychedelic drug experience?,opiods,ASC47_Average,ASC48_Average,ASC49_Average,ASC50_Average,ASC51_Average,ASC52_Average,ASC53_Average,ASC54_Average,EDI9_Average,EDI10_Average,EDI11_Average,EDI12_Average,EDI13_Average,EDI14_Average,EDI15_Average,EDI16_Average,EDI17_Average,Body aches,Sweats or chills,Crying,Feeling hot or cold,MEQ_Total,CEQ_Total,EBI_Total,EDI_Total,ASC_Total
URL Variable: sguid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0BywrMoxyK4CqTMrfzhRpBuPGt96G3J4,532.0,Canada,Toronto,23.0,Male,GB - United Kingdom,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-5 times,NaN,MDMA/Ecstasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0Ck8CVM19UcALyJD3GJeBIGFZfhobzUG,433.0,Canada,NaN,37.0,Male,CA - Canada,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,Salvia Divinorum,NaN,NaN,NaN,NaN,NaN,21-50 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,Benzodiazepines,Ketamine,NaN,NaN,NaN,NaN,Anxiety disorder,Substance abuse disorder,NaN,NaN,NaN,Personality disorder,NaN,NaN,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,100.0,NaN,NaN
0d2Ei33sA5FI6lPfSvj2Cd6WI74Mz8Kn,69.0,Canada,Qu√©bec,35.0,Male,CA - Canada,Post-graduate degree (e.g. masters or doctorate),Full-time job,NaN,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Only once,NaN,NaN,Cocaine,Opiates,Benzodiazepines,NaN,NaN,Major depressive disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Anti-depressants,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,40.0,70.0,NaN,NaN
0GDq2cqvb1Oc9JXfbVHLsgMmKKrriJnb,219.0,United States,Ashburn,37.0,Male,US - United States,Post-graduate degree (e.g. masters or doctorate),Full-time job,LSD,DMT,Ayahuasca,Psilocybin / magic mushrooms / truffles,"Mescaline (Peyote, San Pedro)",NaN,NaN,"Hallucinogen-type NPS (e.g. 25I-NBOMe/N-Bomb, ...",NaN,NaN,NaN,More than 100 times,Amphetamines,MDMA/Ecstasy,Cocaine,Opiates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Psilocybin / magic mushrooms/ truffles,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0HhrbLWHE8U4H89IuzKMG57pDS6ThiMD,231.0,Germany,Frankfurt,23.0,Male,IT - Italy,Bachelor‚Äôs degree (or equivalent),Student,LSD,NaN,NaN,Psilocybin / magic mushrooms / truffles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times,Amphetamines,MDMA/Ecstasy,Cocaine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LSD / 1P-LSD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,0.0,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FnafwU24WNsajpTZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IaIlEW6dlKxpu6SC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J8FRqdya59eAx6Cv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RrmjsV89nn5nri5Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tq7JzFnHzZtTRTj2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Export ceremony data to excel

In [75]:
# Export to excel

ceremony.to_excel("ceremony.xlsx")

## Selecting ceremony columns of interest

In [76]:
c1c2_new.columns.tolist()

['ID_baseline',
 'Country_baseline',
 'City_baseline',
 'age',
 'gender',
 'nationality',
 'education',
 'Employment',
 'LSD use',
 'DMT use',
 'Ayahuasca use',
 'psychedelics use',
 'Mescaline use',
 'Salvia Divinorum use',
 'Iboga use',
 'Hallucinogen use',
 'Other use',
 'None psychedelics use',
 'other1 use',
 'number of times you have taken psychedelic',
 'Amphetamines use',
 'MDMA/Ecstasy use',
 'Cocaine use',
 'Opiates use',
 'Benzodiazepines use',
 'Ketamine use',
 'None drugs use',
 'Major depressive disorder',
 'Bipolar disorder',
 'Schizophrenia',
 'Anxiety disorder',
 'Substance abuse disorder',
 'Alcohol dependence',
 'Hallucinogen persisting perception disorder',
 'Psychotic disorder',
 'Personality disorder',
 'ADHD',
 'Obsessive compulsive disorder',
 'Eating disorder',
 'No disorder',
 'treated with medications',
 'Current use',
 'Anti-depressants',
 'Mood stabilisers',
 'Anti-psychotics',
 'ADHD medication',
 'substance abuse disorder meds',
 'alcohol dependence meds',
 'No current meds',
 'compound to take',
 'other compound',
 'Fun / recreational / party',
 'Therapeutic / personal growth',
 'Medicinal',
 'Spiritual experience',
 'Religious practice',
 'Curiosity',
 'Social',
 'Connection with nature',
 'escape from difficult emotions',
 'confront difficult emotions',
 'WEMWBS1_baseline',
 'WEMWBS2_baseline',
 'WEMWBS3_baseline',
 'WEMWBS4_baseline',
 'WEMWBS5_baseline',
 'WEMWBS6_baseline',
 'WEMWBS7_baseline',
 'WEMWBS8_baseline',
 'WEMWBS9_baseline',
 'WEMWBS10_baseline',
 'WEMWBS11_baseline',
 'WEMWBS12_baseline',
 'WEMWBS13_baseline',
 'WEMWBS14_baseline',
 'ID_acute',
 'Country_acute',
 'used substance',
 'other substance',
 'rote of administration',
 'Other - Write In:How did you administer the drug/medicine?',
 'total dose',
 'exact dose',
 'Cannabis',
 'Alcohol',
 'Stimulants',
 'Tobacco',
 'MDMA/ecstasy',
 'ASC1_Average',
 'ASC2_Average',
 'ASC3_Average',
 'ASC4_Average',
 'ASC5_Average',
 'ASC6_Average',
 'ASC7_Average',
 'ASC8_Average',
 'ASC9_Average',
 'ASC10_Average',
 'ASC11_Average',
 'ASC12_Average',
 'ASC13_Average',
 'ASC14_Average',
 'ASC15_Average',
 'ASC16_Average',
 'ASC17_Average',
 'ASC18_Average',
 'ASC19_Average',
 'ASC20_Average',
 'ASC21_Average',
 'ASC22_Average',
 'ASC23_Average',
 'ASC24_Average',
 'ASC25_Average',
 'ASC26_Average',
 'ASC27_Average',
 'ASC28_Average',
 'ASC29_Average',
 'ASC30_Average',
 'ASC31_Average',
 'ASC32_Average',
 'ASC33_Average',
 'ASC34_Average',
 'ASC35_Average',
 'ASC36_Average',
 'ASC37_Average',
 'ASC38_Average',
 'ASC39_Average',
 'ASC40_Average',
 'ASC41_Average',
 'ASC42_Average',
 'ASC43_Average',
 'ASC44_Average',
 'ASC45_Average',
 'ASC46_Average',
 'MEQ1_Average',
 'MEQ2_Average',
 'MEQ3_Average',
 'MEQ4_Average',
 'MEQ5_Average',
 'MEQ6_Average',
 'MEQ7_Average',
 'MEQ8_Average',
 'MEQ9_Average',
 'MEQ10_Average',
 'MEQ11_Average',
 'MEQ12_Average',
 'MEQ13_Average',
 'MEQ14_Average',
 'MEQ15_Average',
 'MEQ16_Average',
 'MEQ17_Average',
 'MEQ18_Average',
 'MEQ19_Average',
 'MEQ20_Average',
 'MEQ21_Average',
 'MEQ22_Average',
 'MEQ23_Average',
 'MEQ24_Average',
 'MEQ25_Average',
 'MEQ26_Average',
 'MEQ27_Average',
 'MEQ28_Average',
 'MEQ29_Average',
 'MEQ30_Average',
 'nausea',
 'Trouble sleeping',
 'Headache',
 'Acid indigestion or heartbur',
 'Eye strain',
 'Diarrhea',
 'Stomach cramps',
 'Constipation',
 'Ringing in the ears',
 'Loss of appetite',
 'Dizziness',
 'Tiredness or fatigue',
 'EDI1_Average',
 'EDI2_Average',
 'EDI3_Average',
 'EDI4_Average',
 'EDI5_Average',
 'EDI6_Average',
 'EDI7_Average',
 'EDI8_Average',
 'EBI1_Average',
 'EBI2_Average',
 'EBI3_Average',
 'EBI4_Average',
 'EBI5_Average',
 'EBI6_Average',
 'EBI7_Average',
 'EBI8_Average',
 'CEQ1_Average',
 'CEQ2_Average',
 'CEQ3_Average',
 'CEQ4_Average',
 'CEQ5_Average',
 'CEQ6_Average',
 'CEQ7_Average',
 'CEQ8_Average',
 'CEQ9_Average',
 'CEQ10_Average',
 'CEQ11_Average',
 'CEQ12_Average',
 'CEQ13_Average',
 'CEQ14_Average',
 'CEQ15_Average',
 'CEQ16_Average',
 'CEQ17_Average',
 'CEQ18_Average',
 'CEQ19_Average',
 'CEQ20_Average',
 'CEQ21_Average',
 'CEQ22_Average',
 'CEQ23_Average',
 'CEQ24_Average',
 'CEQ25_Average',
 'CEQ26_Average',
 'ID_post',
 'Country_post',
 'City_post',
 'State/Region',
 'Postal',
 'URL Variable: date',
 'URL Variable: email',
 'WEMWBS1_post',
 'WEMWBS2_post',
 'WEMWBS3_post',
 'WEMWBS4_post',
 'WEMWBS5_post',
 'WEMWBS6_post',
 'WEMWBS7_post',
 'WEMWBS8_post',
 'WEMWBS9_post',
 'WEMWBS10_post',
 'WEMWBS11_post',
 'WEMWBS12_post',
 'WEMWBS13_post',
 'WEMWBS14_post',
 'White',
 'Black or African American',
 'Asian',
 'American Indian or Alaskan Native',
 'Native Hawaiian or Other Pacific Islander',
 'Unknown',
 'Not say',
 'Have you ever been treated with any kind of psychiatric medication (e.g. antidepressants, antipsychotics, ADHD medication, mood stabilisers)?',
 'Fluoxetine:What is your currently prescribed anti-depressant? Please tick',
 'Citalopram:What is your currently prescribed anti-depressant? Please tick',
 'Sertraline:What is your currently prescribed anti-depressant? Please tick',
 'Paroxetine:What is your currently prescribed anti-depressant? Please tick',
 'Escitalopram:What is your currently prescribed anti-depressant? Please tick',
 'Venlafaxine:What is your currently prescribed anti-depressant? Please tick',
 'Duloxetine:What is your currently prescribed anti-depressant? Please tick',
 'Trazadone:What is your currently prescribed anti-depressant? Please tick',
 'Mirtazapine:What is your currently prescribed anti-depressant? Please tick',
 'Other - Write In:What is your currently prescribed anti-depressant? Please tick',
 'Other - Write In:What is your currently prescribed anti-depressant? Please tick.1',
 'how long',
 'plan to continue antidepressants',
 'spiritual healing',
 'Treatment of mental health problems',
 'Healing physical illness',
 'Spiritual experience:Can you indicate what your motives are to undergo a psychedelic ceremony?',
 'Communication with the spirit world',
 'How did you administer the drug?',
 'Other - Write In:How did you administer the drug?',
 'Can you indicate what (total) dose you used? To standardise responses, we will ask you to answer in reference to typical doses of LSD.* For example, 1 typical tab or ‚Äúhit‚Äù of LSD usually contains approximately 50-100 micrograms. If you do not know what a typical dose of LSD is like, you could consider asking someone who does know. *DISCLAIMER: We are aware that this approach of assessing the drug dose you used is imperfect, but done for calibration purposes to one drug of reference (here: LSD).¬† ¬†',
 'How intense would you rate your psychedelic drug experience?',
 'opiods',
 'ASC47_Average',
 'ASC48_Average',
 'ASC49_Average',
 'ASC50_Average',
 'ASC51_Average',
 'ASC52_Average',
 'ASC53_Average',
 'ASC54_Average',
 'EDI9_Average',
 'EDI10_Average',
 'EDI11_Average',
 'EDI12_Average',
 'EDI13_Average',
 'EDI14_Average',
 'EDI15_Average',
 'EDI16_Average',
 'EDI17_Average',
 'Body aches',
 'Sweats or chills',
 'Crying',
 'Feeling hot or cold',
 'MEQ_Total',
 'CEQ_Total',
 'EBI_Total',
 'EDI_Total',
 'ASC_Total']

In [77]:
# View all columns that are the same between c1c2_new and ceremony data

ceremony.columns.intersection(c1c2_new.columns).tolist()

['ID_baseline',
 'Country_baseline',
 'State/Region',
 'Postal',
 'age',
 'gender',
 'nationality',
 'education',
 'Employment',
 'White',
 'Black or African American',
 'Asian',
 'American Indian or Alaskan Native',
 'Native Hawaiian or Other Pacific Islander',
 'Unknown',
 'Not say',
 'LSD use',
 'DMT use',
 'Ayahuasca use',
 'psychedelics use',
 'Mescaline use',
 'Salvia Divinorum use',
 'Iboga use',
 'Hallucinogen use',
 'Other use',
 'other1 use',
 'number of times you have taken psychedelic',
 'Amphetamines use',
 'MDMA/Ecstasy use',
 'Cocaine use',
 'Opiates use',
 'Benzodiazepines use',
 'Ketamine use',
 'Major depressive disorder',
 'Bipolar disorder',
 'Schizophrenia',
 'Anxiety disorder',
 'Substance abuse disorder',
 'Alcohol dependence',
 'Hallucinogen persisting perception disorder',
 'Psychotic disorder',
 'Personality disorder',
 'ADHD',
 'Obsessive compulsive disorder',
 'Eating disorder',
 'No disorder',
 'treated with medications',
 'Current use',
 'Anti-depressants',
 'Mood stabilisers',
 'Anti-psychotics',
 'ADHD medication',
 'substance abuse disorder meds',
 'alcohol dependence meds',
 'No current meds',
 'how long',
 'plan to continue antidepressants',
 'compound to take',
 'other compound',
 'Fun / recreational / party',
 'spiritual healing',
 'Treatment of mental health problems',
 'Healing physical illness',
 'Religious practice',
 'Curiosity',
 'Social',
 'Connection with nature',
 'Communication with the spirit world',
 'escape from difficult emotions',
 'WEMWBS1_baseline',
 'WEMWBS2_baseline',
 'WEMWBS3_baseline',
 'WEMWBS4_baseline',
 'WEMWBS5_baseline',
 'WEMWBS6_baseline',
 'WEMWBS7_baseline',
 'WEMWBS8_baseline',
 'WEMWBS9_baseline',
 'WEMWBS10_baseline',
 'WEMWBS11_baseline',
 'WEMWBS12_baseline',
 'WEMWBS13_baseline',
 'WEMWBS14_baseline',
 'ID_post',
 'WEMWBS1_post',
 'WEMWBS2_post',
 'WEMWBS3_post',
 'WEMWBS4_post',
 'WEMWBS5_post',
 'WEMWBS6_post',
 'WEMWBS7_post',
 'WEMWBS8_post',
 'WEMWBS9_post',
 'WEMWBS10_post',
 'WEMWBS11_post',
 'WEMWBS12_post',
 'WEMWBS13_post',
 'WEMWBS14_post',
 'MEQ1_Average',
 'MEQ2_Average',
 'MEQ3_Average',
 'MEQ4_Average',
 'MEQ5_Average',
 'MEQ6_Average',
 'MEQ7_Average',
 'MEQ8_Average',
 'MEQ9_Average',
 'MEQ10_Average',
 'MEQ11_Average',
 'MEQ12_Average',
 'MEQ13_Average',
 'MEQ14_Average',
 'MEQ15_Average',
 'MEQ16_Average',
 'MEQ17_Average',
 'MEQ18_Average',
 'MEQ19_Average',
 'MEQ20_Average',
 'MEQ21_Average',
 'MEQ22_Average',
 'MEQ23_Average',
 'MEQ24_Average',
 'MEQ25_Average',
 'MEQ26_Average',
 'MEQ27_Average',
 'MEQ28_Average',
 'MEQ29_Average',
 'MEQ30_Average',
 'MEQ_Total',
 'CEQ1_Average',
 'CEQ2_Average',
 'CEQ3_Average',
 'CEQ4_Average',
 'CEQ5_Average',
 'CEQ6_Average',
 'CEQ7_Average',
 'CEQ8_Average',
 'CEQ9_Average',
 'CEQ10_Average',
 'CEQ11_Average',
 'CEQ12_Average',
 'CEQ13_Average',
 'CEQ14_Average',
 'CEQ15_Average',
 'CEQ16_Average',
 'CEQ17_Average',
 'CEQ18_Average',
 'CEQ19_Average',
 'CEQ20_Average',
 'CEQ21_Average',
 'CEQ22_Average',
 'CEQ23_Average',
 'CEQ24_Average',
 'CEQ25_Average',
 'CEQ26_Average',
 'CEQ_Total',
 'EBI1_Average',
 'EBI2_Average',
 'EBI3_Average',
 'EBI4_Average',
 'EBI5_Average',
 'EBI6_Average',
 'EBI7_Average',
 'EBI8_Average',
 'EBI_Total',
 'EDI1_Average',
 'EDI2_Average',
 'EDI3_Average',
 'EDI4_Average',
 'EDI5_Average',
 'EDI6_Average',
 'EDI7_Average',
 'EDI8_Average',
 'EDI9_Average',
 'EDI10_Average',
 'EDI11_Average',
 'EDI12_Average',
 'EDI13_Average',
 'EDI14_Average',
 'EDI15_Average',
 'EDI16_Average',
 'EDI_Total',
 'ASC1_Average',
 'ASC2_Average',
 'ASC3_Average',
 'ASC4_Average',
 'ASC5_Average',
 'ASC6_Average',
 'ASC7_Average',
 'ASC8_Average',
 'ASC9_Average',
 'ASC_Total']

In [78]:
# What columns are present in ceremony and not in c1c2_new
# Please review if any of these columns are of interest

ceremony.columns.difference(c1c2_new.columns).tolist()

['1. Seeing bursts of light or splashes of colour._2',
 '1. Seeing bursts of light or splashes of colour._3',
 '1. Seeing bursts of light or splashes of colour._4',
 '1. Seeing bursts of light or splashes of colour._5',
 '10. Visions with personal/autobiographic material._2',
 '10. Visions with personal/autobiographic material._3',
 '10. Visions with personal/autobiographic material._4',
 '10. Visions with personal/autobiographic material._5',
 '11. Interacting with beings/entities in your visions._2',
 '11. Interacting with beings/entities in your visions._3',
 '11. Interacting with beings/entities in your visions._4',
 '11. Interacting with beings/entities in your visions._5',
 '12. Visions with sacred or divine themes._2',
 '12. Visions with sacred or divine themes._3',
 '12. Visions with sacred or divine themes._4',
 '12. Visions with sacred or divine themes._5',
 '13. Visions with carnivalesque or tricksterish themes._2',
 '13. Visions with carnivalesque or tricksterish themes._3',
 '13. Visions with carnivalesque or tricksterish themes._4',
 '13. Visions with carnivalesque or tricksterish themes._5',
 '14. Visions with demonic or evil themes._2',
 '14. Visions with demonic or evil themes._3',
 '14. Visions with demonic or evil themes._4',
 '14. Visions with demonic or evil themes._5',
 '15. Visions of nature, animals or plants._2',
 '15. Visions of nature, animals or plants._3',
 '15. Visions of nature, animals or plants._4',
 '15. Visions of nature, animals or plants._5',
 '16. Important knowledge being conveyed to you through your visions._2',
 '16. Important knowledge being conveyed to you through your visions._3',
 '16. Important knowledge being conveyed to you through your visions._4',
 '16. Important knowledge being conveyed to you through your visions._5',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._2',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._3',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._4',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._5',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._2',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._3',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._4',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._5',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '2. Seeing abstract geometrical designs and patterns._2',
 '2. Seeing abstract geometrical designs and patterns._3',
 '2. Seeing abstract geometrical designs and patterns._4',
 '2. Seeing abstract geometrical designs and patterns._5',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '3. Seeing rapidly transforming objects/figures._2',
 '3. Seeing rapidly transforming objects/figures._3',
 '3. Seeing rapidly transforming objects/figures._4',
 '3. Seeing rapidly transforming objects/figures._5',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._2',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._3',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._4',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._5',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '5. Seeing stable, well-defined objects/figures_2',
 '5. Seeing stable, well-defined objects/figures_3',
 '5. Seeing stable, well-defined objects/figures_4',
 '5. Seeing stable, well-defined objects/figures_5',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '6. Seeing snapshots or glimpses of full scenes._2',
 '6. Seeing snapshots or glimpses of full scenes._3',
 '6. Seeing snapshots or glimpses of full scenes._4',
 '6. Seeing snapshots or glimpses of full scenes._5',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._2',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._3',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._4',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._5',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '8. Being fully immersed within what looked and felt like another authentic realm._2',
 '8. Being fully immersed within what looked and felt like another authentic realm._3',
 '8. Being fully immersed within what looked and felt like another authentic realm._4',
 '8. Being fully immersed within what looked and felt like another authentic realm._5',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '9. Being surrounded by a supreme white light._2',
 '9. Being surrounded by a supreme white light._3',
 '9. Being surrounded by a supreme white light._4',
 '9. Being surrounded by a supreme white light._5',
 'ASC1_1',
 'ASC1_2',
 'ASC1_3',
 'ASC1_4',
 'ASC1_5',
 'ASC2_1',
 'ASC2_2',
 'ASC2_3',
 'ASC2_4',
 'ASC2_5',
 'ASC3_1',
 'ASC3_2',
 'ASC3_3',
 'ASC3_4',
 'ASC3_5',
 'ASC4_1',
 'ASC4_2',
 'ASC4_3',
 'ASC4_4',
 'ASC4_5',
 'ASC5_1',
 'ASC5_2',
 'ASC5_3',
 'ASC5_4',
 'ASC5_5',
 'ASC6_1',
 'ASC6_2',
 'ASC6_3',
 'ASC6_4',
 'ASC6_5',
 'ASC7_1',
 'ASC7_2',
 'ASC7_3',
 'ASC7_4',
 'ASC7_5',
 'ASC8_1',
 'ASC8_2',
 'ASC8_3',
 'ASC8_4',
 'ASC8_5',
 'ASC9_1',
 'ASC9_2',
 'ASC9_3',
 'ASC9_4',
 'ASC9_5',
 'Acacia / Chocolate with Mushroom 35% Ayausca 65%:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_2',
 'Alcohol_1',
 'Alcohol_2',
 'Alcohol_3',
 'Alcohol_4',
 'Alcohol_5',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_2',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_3',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_4',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_2',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_3',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_4',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._2',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._3',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._4',
 'Aya:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Ayahuasca_1',
 'Ayahuasca_2',
 'Ayahuasca_3',
 'B.capi and P.viridis:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Blue lotus, cbd oil:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Body aches_1',
 'Body aches_2',
 'Body aches_3',
 'Body aches_4',
 'Body aches_5',
 'CEQ10_1',
 'CEQ10_2',
 'CEQ10_3',
 'CEQ10_4',
 'CEQ10_5',
 'CEQ11_1',
 'CEQ11_2',
 'CEQ11_3',
 'CEQ11_4',
 'CEQ11_5',
 'CEQ12_1',
 'CEQ12_2',
 'CEQ12_3',
 'CEQ12_4',
 'CEQ12_5',
 'CEQ13_1',
 'CEQ13_2',
 'CEQ13_3',
 'CEQ13_4',
 'CEQ13_5',
 'CEQ14_1',
 'CEQ14_2',
 'CEQ14_3',
 'CEQ14_4',
 'CEQ14_5',
 'CEQ15_1',
 'CEQ15_2',
 'CEQ15_3',
 'CEQ15_4',
 'CEQ15_5',
 'CEQ16_1',
 'CEQ16_2',
 'CEQ16_3',
 'CEQ16_4',
 'CEQ16_5',
 'CEQ17_1',
 'CEQ17_2',
 'CEQ17_3',
 'CEQ17_4',
 'CEQ17_5',
 'CEQ18_1',
 'CEQ18_2',
 'CEQ18_3',
 'CEQ18_4',
 'CEQ18_5',
 'CEQ19_1',
 'CEQ19_2',
 'CEQ19_3',
 'CEQ19_4',
 'CEQ19_5',
 'CEQ1_1',
 'CEQ1_2',
 'CEQ1_3',
 'CEQ1_4',
 'CEQ1_5',
 'CEQ20_1',
 'CEQ20_2',
 'CEQ20_3',
 'CEQ20_4',
 'CEQ20_5',
 'CEQ21_1',
 'CEQ21_2',
 'CEQ21_3',
 'CEQ21_4',
 'CEQ21_5',
 'CEQ22_1',
 'CEQ22_2',
 'CEQ22_3',
 'CEQ22_4',
 'CEQ22_5',
 'CEQ23_1',
 'CEQ23_2',
 'CEQ23_3',
 'CEQ23_4',
 'CEQ23_5',
 'CEQ24_1',
 'CEQ24_2',
 'CEQ24_3',
 'CEQ24_4',
 'CEQ24_5',
 'CEQ25_1',
 'CEQ25_2',
 'CEQ25_3',
 'CEQ25_4',
 'CEQ25_5',
 'CEQ26_1',
 'CEQ26_2',
 'CEQ26_3',
 'CEQ26_4',
 'CEQ26_5',
 'CEQ2_1',
 'CEQ2_2',
 'CEQ2_3',
 'CEQ2_4',
 'CEQ2_5',
 'CEQ3_1',
 'CEQ3_2',
 'CEQ3_3',
 'CEQ3_4',
 'CEQ3_5',
 'CEQ4_1',
 'CEQ4_2',
 'CEQ4_3',
 'CEQ4_4',
 'CEQ4_5',
 'CEQ5_1',
 'CEQ5_2',
 'CEQ5_3',
 'CEQ5_4',
 'CEQ5_5',
 'CEQ6_1',
 'CEQ6_2',
 'CEQ6_3',
 'CEQ6_4',
 'CEQ6_5',
 'CEQ7_1',
 'CEQ7_2',
 'CEQ7_3',
 'CEQ7_4',
 'CEQ7_5',
 'CEQ8_1',
 'CEQ8_2',
 'CEQ8_3',
 'CEQ8_4',
 'CEQ8_5',
 'CEQ9_1',
 'CEQ9_2',
 'CEQ9_3',
 'CEQ9_4',
 'CEQ9_5',
 'Can you indicate how many more experiences you have had within the past two weeks/since the last questionnaire?',
 'Cannabis:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?.1_2',
 'Cannabis_1',
 'Cannabis_2',
 'Cannabis_3',
 'Cannabis_4',
 'Cannabis_5',
 'City',
 'City_1',
 'City_2',
 'City_3',
 'City_4',
 'City_5',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_2',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_3',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_4',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_5',
 'Coca_1',
 'Comments',
 'Comments_2',
 'Comments_3',
 'Comments_4',
 'Contact ID',
 'Contact ID_2',
 'Contact ID_3',
 'Contact ID_4',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Country',
 'Country_1',
 'Country_2',
 'Country_3',
 'Country_4',
 'Country_5',
 'Crying_1',
 'Crying_2',
 'Crying_3',
 'Crying_4',
 'Crying_5',
 'DMT_1',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Date Submitted',
 'Date Submitted_1',
 'Date Submitted_2',
 'Date Submitted_3',
 'Date Submitted_4',
 'Date Submitted_5',
 'Diarrhea_1',
 'Diarrhea_2',
 'Diarrhea_3',
 'Diarrhea_4',
 'Diarrhea_5',
 'Did you experience the vomiting, diarrhea, sweating or crying as transformative (i.e. cleansing, or "purging")?_1',
 'Did you experience the vomiting, diarrhea, sweating or crying as transformative (i.e. cleansing, or "purging")?_2',

In [86]:
# This is my version of the columns to select, based on the columns 
# already overlapping between cohort1/2 and ceremony

ceremony_new = ceremony[['ID_baseline',
 'Country_baseline',
 'State/Region',
 'Postal',
 'age',
 'gender',
 'nationality',
 'education',
 'Employment',
 'White',
 'Black or African American',
 'Asian',
 'American Indian or Alaskan Native',
 'Native Hawaiian or Other Pacific Islander',
 'Unknown',
 'Not say',
 'LSD use',
 'DMT use',
 'Ayahuasca use',
 'psychedelics use',
 'Mescaline use',
 'Salvia Divinorum use',
 'Iboga use',
 'Hallucinogen use',
 'Other use',
 'other1 use',
 'number of times you have taken psychedelic',
 'Amphetamines use',
 'MDMA/Ecstasy use',
 'Cocaine use',
 'Opiates use',
 'Benzodiazepines use',
 'Ketamine use',
 'Major depressive disorder',
 'Bipolar disorder',
 'Schizophrenia',
 'Anxiety disorder',
 'Substance abuse disorder',
 'Alcohol dependence',
 'Hallucinogen persisting perception disorder',
 'Psychotic disorder',
 'Personality disorder',
 'ADHD',
 'Obsessive compulsive disorder',
 'Eating disorder',
 'No disorder',
 'treated with medications',
 'Current use',
 'Anti-depressants',
 'Mood stabilisers',
 'Anti-psychotics',
 'ADHD medication',
 'substance abuse disorder meds',
 'alcohol dependence meds',
 'No current meds',
 'how long',
 'plan to continue antidepressants',
 'compound to take',
 'other compound',
 'Fun / recreational / party',
 'spiritual healing',
 'Treatment of mental health problems',
 'Healing physical illness',
 'Religious practice',
 'Curiosity',
 'Social',
 'Connection with nature',
 'Communication with the spirit world',
 'escape from difficult emotions',
 'WEMWBS1_baseline',
 'WEMWBS2_baseline',
 'WEMWBS3_baseline',
 'WEMWBS4_baseline',
 'WEMWBS5_baseline',
 'WEMWBS6_baseline',
 'WEMWBS7_baseline',
 'WEMWBS8_baseline',
 'WEMWBS9_baseline',
 'WEMWBS10_baseline',
 'WEMWBS11_baseline',
 'WEMWBS12_baseline',
 'WEMWBS13_baseline',
 'WEMWBS14_baseline',
 'ID_post',
 'WEMWBS1_post',
 'WEMWBS2_post',
 'WEMWBS3_post',
 'WEMWBS4_post',
 'WEMWBS5_post',
 'WEMWBS6_post',
 'WEMWBS7_post',
 'WEMWBS8_post',
 'WEMWBS9_post',
 'WEMWBS10_post',
 'WEMWBS11_post',
 'WEMWBS12_post',
 'WEMWBS13_post',
 'WEMWBS14_post',
 'MEQ1_Average',
 'MEQ2_Average',
 'MEQ3_Average',
 'MEQ4_Average',
 'MEQ5_Average',
 'MEQ6_Average',
 'MEQ7_Average',
 'MEQ8_Average',
 'MEQ9_Average',
 'MEQ10_Average',
 'MEQ11_Average',
 'MEQ12_Average',
 'MEQ13_Average',
 'MEQ14_Average',
 'MEQ15_Average',
 'MEQ16_Average',
 'MEQ17_Average',
 'MEQ18_Average',
 'MEQ19_Average',
 'MEQ20_Average',
 'MEQ21_Average',
 'MEQ22_Average',
 'MEQ23_Average',
 'MEQ24_Average',
 'MEQ25_Average',
 'MEQ26_Average',
 'MEQ27_Average',
 'MEQ28_Average',
 'MEQ29_Average',
 'MEQ30_Average',
 'MEQ_Total',
 'CEQ1_Average',
 'CEQ2_Average',
 'CEQ3_Average',
 'CEQ4_Average',
 'CEQ5_Average',
 'CEQ6_Average',
 'CEQ7_Average',
 'CEQ8_Average',
 'CEQ9_Average',
 'CEQ10_Average',
 'CEQ11_Average',
 'CEQ12_Average',
 'CEQ13_Average',
 'CEQ14_Average',
 'CEQ15_Average',
 'CEQ16_Average',
 'CEQ17_Average',
 'CEQ18_Average',
 'CEQ19_Average',
 'CEQ20_Average',
 'CEQ21_Average',
 'CEQ22_Average',
 'CEQ23_Average',
 'CEQ24_Average',
 'CEQ25_Average',
 'CEQ26_Average',
 'CEQ_Total',
 'EBI1_Average',
 'EBI2_Average',
 'EBI3_Average',
 'EBI4_Average',
 'EBI5_Average',
 'EBI6_Average',
 'EBI7_Average',
 'EBI8_Average',
 'EBI_Total',
 'EDI1_Average',
 'EDI2_Average',
 'EDI3_Average',
 'EDI4_Average',
 'EDI5_Average',
 'EDI6_Average',
 'EDI7_Average',
 'EDI8_Average',
 'EDI9_Average',
 'EDI10_Average',
 'EDI11_Average',
 'EDI12_Average',
 'EDI13_Average',
 'EDI14_Average',
 'EDI15_Average',
 'EDI16_Average',
 'EDI_Total',
 'ASC1_Average',
 'ASC2_Average',
 'ASC3_Average',
 'ASC4_Average',
 'ASC5_Average',
 'ASC6_Average',
 'ASC7_Average',
 'ASC8_Average',
 'ASC9_Average',
 'ASC_Total']]

In [87]:
getDuplicateColumns(ceremony_new)

['substance abuse disorder meds', 'EBI_Total', 'EDI_Total']

In [88]:
ceremony_new = ceremony_new.loc[:,~ceremony_new.columns.duplicated(keep='first')]

## Export to excel

In [89]:
all_data = pd.concat([c1c2_new, ceremony_new], axis=0)

In [91]:
# This exports our dataframe into excel format.
# We need to specify which dataframe we want to export, 
# And in brackets provide the name of the new excel file 
# that we want to create. 

all_data.to_excel("all_data.xlsx")

# Draft notes

In [79]:
# What columns are present in ceremony and not in c1c2_new?
# Might want to have a look if any of these are of interest. 
# We can then try to integrate them. 

ceremony.columns.difference(c1c2_new.columns).tolist()

['1. Seeing bursts of light or splashes of colour._2',
 '1. Seeing bursts of light or splashes of colour._3',
 '1. Seeing bursts of light or splashes of colour._4',
 '1. Seeing bursts of light or splashes of colour._5',
 '10. Visions with personal/autobiographic material._2',
 '10. Visions with personal/autobiographic material._3',
 '10. Visions with personal/autobiographic material._4',
 '10. Visions with personal/autobiographic material._5',
 '11. Interacting with beings/entities in your visions._2',
 '11. Interacting with beings/entities in your visions._3',
 '11. Interacting with beings/entities in your visions._4',
 '11. Interacting with beings/entities in your visions._5',
 '12. Visions with sacred or divine themes._2',
 '12. Visions with sacred or divine themes._3',
 '12. Visions with sacred or divine themes._4',
 '12. Visions with sacred or divine themes._5',
 '13. Visions with carnivalesque or tricksterish themes._2',
 '13. Visions with carnivalesque or tricksterish themes._3',
 '13. Visions with carnivalesque or tricksterish themes._4',
 '13. Visions with carnivalesque or tricksterish themes._5',
 '14. Visions with demonic or evil themes._2',
 '14. Visions with demonic or evil themes._3',
 '14. Visions with demonic or evil themes._4',
 '14. Visions with demonic or evil themes._5',
 '15. Visions of nature, animals or plants._2',
 '15. Visions of nature, animals or plants._3',
 '15. Visions of nature, animals or plants._4',
 '15. Visions of nature, animals or plants._5',
 '16. Important knowledge being conveyed to you through your visions._2',
 '16. Important knowledge being conveyed to you through your visions._3',
 '16. Important knowledge being conveyed to you through your visions._4',
 '16. Important knowledge being conveyed to you through your visions._5',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._2',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._3',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._4',
 '17.¬†Visions progressing over time from simple (busts/splashes/geometries) to complex (well-defined objects/figures) images._5',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._2',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._3',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._4',
 '18.¬†Visions progressing over time from isolated elements to full, immersive scenes._5',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '1:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '2. Seeing abstract geometrical designs and patterns._2',
 '2. Seeing abstract geometrical designs and patterns._3',
 '2. Seeing abstract geometrical designs and patterns._4',
 '2. Seeing abstract geometrical designs and patterns._5',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '2:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '3. Seeing rapidly transforming objects/figures._2',
 '3. Seeing rapidly transforming objects/figures._3',
 '3. Seeing rapidly transforming objects/figures._4',
 '3. Seeing rapidly transforming objects/figures._5',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '3:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._2',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._3',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._4',
 '4. Seeing repetitive, moving objects/figures embedded in geometrical patterns._5',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '4:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '5. Seeing stable, well-defined objects/figures_2',
 '5. Seeing stable, well-defined objects/figures_3',
 '5. Seeing stable, well-defined objects/figures_4',
 '5. Seeing stable, well-defined objects/figures_5',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '5:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '6. Seeing snapshots or glimpses of full scenes._2',
 '6. Seeing snapshots or glimpses of full scenes._3',
 '6. Seeing snapshots or glimpses of full scenes._4',
 '6. Seeing snapshots or glimpses of full scenes._5',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '6:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._2',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._3',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._4',
 '7. Seeing full-fledged scenes without being part of them, similar to watching a movie._5',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '7:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '8. Being fully immersed within what looked and felt like another authentic realm._2',
 '8. Being fully immersed within what looked and felt like another authentic realm._3',
 '8. Being fully immersed within what looked and felt like another authentic realm._4',
 '8. Being fully immersed within what looked and felt like another authentic realm._5',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._2',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._3',
 '8:Please make sure that resolution and brightness of the pictures are good enough for us to read your answers.¬† You can upload the pictures of this questionnaire page by page (max 8) or appended into a single file (max 10MB). Accepted formats are png, jpg, jpeg and pdf._4',
 '9. Being surrounded by a supreme white light._2',
 '9. Being surrounded by a supreme white light._3',
 '9. Being surrounded by a supreme white light._4',
 '9. Being surrounded by a supreme white light._5',
 'ASC1_1',
 'ASC1_2',
 'ASC1_3',
 'ASC1_4',
 'ASC1_5',
 'ASC2_1',
 'ASC2_2',
 'ASC2_3',
 'ASC2_4',
 'ASC2_5',
 'ASC3_1',
 'ASC3_2',
 'ASC3_3',
 'ASC3_4',
 'ASC3_5',
 'ASC4_1',
 'ASC4_2',
 'ASC4_3',
 'ASC4_4',
 'ASC4_5',
 'ASC5_1',
 'ASC5_2',
 'ASC5_3',
 'ASC5_4',
 'ASC5_5',
 'ASC6_1',
 'ASC6_2',
 'ASC6_3',
 'ASC6_4',
 'ASC6_5',
 'ASC7_1',
 'ASC7_2',
 'ASC7_3',
 'ASC7_4',
 'ASC7_5',
 'ASC8_1',
 'ASC8_2',
 'ASC8_3',
 'ASC8_4',
 'ASC8_5',
 'ASC9_1',
 'ASC9_2',
 'ASC9_3',
 'ASC9_4',
 'ASC9_5',
 'Acacia / Chocolate with Mushroom 35% Ayausca 65%:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_2',
 'Alcohol_1',
 'Alcohol_2',
 'Alcohol_3',
 'Alcohol_4',
 'Alcohol_5',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_2',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_3',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply..1_4',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Another activity - Write In:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_2',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_3',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply..1_4',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._2',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._3',
 'Another component - Write In:From the following list, please select those components that were present at some stage during the session / ceremony. Please tick all boxes that apply._4',
 'Aya:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Ayahuasca_1',
 'Ayahuasca_2',
 'Ayahuasca_3',
 'B.capi and P.viridis:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Blue lotus, cbd oil:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_1',
 'Body aches_1',
 'Body aches_2',
 'Body aches_3',
 'Body aches_4',
 'Body aches_5',
 'CEQ10_1',
 'CEQ10_2',
 'CEQ10_3',
 'CEQ10_4',
 'CEQ10_5',
 'CEQ11_1',
 'CEQ11_2',
 'CEQ11_3',
 'CEQ11_4',
 'CEQ11_5',
 'CEQ12_1',
 'CEQ12_2',
 'CEQ12_3',
 'CEQ12_4',
 'CEQ12_5',
 'CEQ13_1',
 'CEQ13_2',
 'CEQ13_3',
 'CEQ13_4',
 'CEQ13_5',
 'CEQ14_1',
 'CEQ14_2',
 'CEQ14_3',
 'CEQ14_4',
 'CEQ14_5',
 'CEQ15_1',
 'CEQ15_2',
 'CEQ15_3',
 'CEQ15_4',
 'CEQ15_5',
 'CEQ16_1',
 'CEQ16_2',
 'CEQ16_3',
 'CEQ16_4',
 'CEQ16_5',
 'CEQ17_1',
 'CEQ17_2',
 'CEQ17_3',
 'CEQ17_4',
 'CEQ17_5',
 'CEQ18_1',
 'CEQ18_2',
 'CEQ18_3',
 'CEQ18_4',
 'CEQ18_5',
 'CEQ19_1',
 'CEQ19_2',
 'CEQ19_3',
 'CEQ19_4',
 'CEQ19_5',
 'CEQ1_1',
 'CEQ1_2',
 'CEQ1_3',
 'CEQ1_4',
 'CEQ1_5',
 'CEQ20_1',
 'CEQ20_2',
 'CEQ20_3',
 'CEQ20_4',
 'CEQ20_5',
 'CEQ21_1',
 'CEQ21_2',
 'CEQ21_3',
 'CEQ21_4',
 'CEQ21_5',
 'CEQ22_1',
 'CEQ22_2',
 'CEQ22_3',
 'CEQ22_4',
 'CEQ22_5',
 'CEQ23_1',
 'CEQ23_2',
 'CEQ23_3',
 'CEQ23_4',
 'CEQ23_5',
 'CEQ24_1',
 'CEQ24_2',
 'CEQ24_3',
 'CEQ24_4',
 'CEQ24_5',
 'CEQ25_1',
 'CEQ25_2',
 'CEQ25_3',
 'CEQ25_4',
 'CEQ25_5',
 'CEQ26_1',
 'CEQ26_2',
 'CEQ26_3',
 'CEQ26_4',
 'CEQ26_5',
 'CEQ2_1',
 'CEQ2_2',
 'CEQ2_3',
 'CEQ2_4',
 'CEQ2_5',
 'CEQ3_1',
 'CEQ3_2',
 'CEQ3_3',
 'CEQ3_4',
 'CEQ3_5',
 'CEQ4_1',
 'CEQ4_2',
 'CEQ4_3',
 'CEQ4_4',
 'CEQ4_5',
 'CEQ5_1',
 'CEQ5_2',
 'CEQ5_3',
 'CEQ5_4',
 'CEQ5_5',
 'CEQ6_1',
 'CEQ6_2',
 'CEQ6_3',
 'CEQ6_4',
 'CEQ6_5',
 'CEQ7_1',
 'CEQ7_2',
 'CEQ7_3',
 'CEQ7_4',
 'CEQ7_5',
 'CEQ8_1',
 'CEQ8_2',
 'CEQ8_3',
 'CEQ8_4',
 'CEQ8_5',
 'CEQ9_1',
 'CEQ9_2',
 'CEQ9_3',
 'CEQ9_4',
 'CEQ9_5',
 'Can you indicate how many more experiences you have had within the past two weeks/since the last questionnaire?',
 'Cannabis:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?.1_2',
 'Cannabis_1',
 'Cannabis_2',
 'Cannabis_3',
 'Cannabis_4',
 'Cannabis_5',
 'City',
 'City_1',
 'City_2',
 'City_3',
 'City_4',
 'City_5',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_2',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_3',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_4',
 'Coca:Can you indicate what other types of substances / plant medicines (incl. the dose) you used during the ceremony?_5',
 'Coca_1',
 'Comments',
 'Comments_2',
 'Comments_3',
 'Comments_4',
 'Contact ID',
 'Contact ID_2',
 'Contact ID_3',
 'Contact ID_4',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Conversations:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Country',
 'Country_1',
 'Country_2',
 'Country_3',
 'Country_4',
 'Country_5',
 'Crying_1',
 'Crying_2',
 'Crying_3',
 'Crying_4',
 'Crying_5',
 'DMT_1',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._2',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._3',
 'Dancing:From the following list, please select those activities that any members of the group (not including facilitators or shamans) participated in¬†at some stage during the ceremony. Please tick all boxes that apply._4',
 'Date Submitted',
 'Date Submitted_1',
 'Date Submitted_2',
 'Date Submitted_3',
 'Date Submitted_4',
 'Date Submitted_5',
 'Diarrhea_1',
 'Diarrhea_2',
 'Diarrhea_3',
 'Diarrhea_4',
 'Diarrhea_5',
 'Did you experience the vomiting, diarrhea, sweating or crying as transformative (i.e. cleansing, or "purging")?_1',
 'Did you experience the vomiting, diarrhea, sweating or crying as transformative (i.e. cleansing, or "purging")?_2',